import { MORE } from "./catalog-more";
import { inferProvenance, inferRoles } from "./provenance";

export type Genre =
  | "games"
  | "social"
  | "productivity"
  | "tools"
  | "photo"
  | "music"
  | "entertainment"
  | "education"
  | "health"
  | "finance"
  | "shopping"
  | "news"
  | "travel"
  | "maps"
  | "food"
  | "weather"
  | "business"
  | "lifestyle"
  | "kids"
  | "video"
  | "communication"
  | "personalization"
  | "libraries"
  | "coming-soon";

export type AppEntry = {
  id: string;
  name: string;
  tagline: string;
  description: string;
  url: string;
  developer: string;
  genres: Genre[];
  offline?: boolean;
  installable?: boolean;
  aiBuilt?: boolean;
  featured?: boolean;
  sponsored?: boolean;
  editorsPick?: boolean;
  paid?: boolean;
  comingSoon?: boolean;
  source?: string;
  platform?: string;
  iconUrl?: string;
  rating: number;
  ratingsCount: number;
  clicks?: number;
  ownerId?: string;
  provenance?: "vibe" | "pro";
  roles?: string[];
  tags?: string[];
};

export const GENRE_META: Record<Genre, { label: string; hint: string; tone: string }> = {
  games: { label: "Games", hint: "Play in the browser", tone: "coral" },
  social: { label: "Social", hint: "People and rooms", tone: "rose" },
  productivity: { label: "Productivity", hint: "Get it done", tone: "sky" },
  tools: { label: "Tools", hint: "One job, well", tone: "slate" },
  photo: { label: "Photo", hint: "Capture and edit", tone: "amber" },
  music: { label: "Music", hint: "Sound and karaoke", tone: "rose" },
  entertainment: { label: "Entertainment", hint: "Watch and wander", tone: "indigo" },
  education: { label: "Education", hint: "Learn something", tone: "teal" },
  health: { label: "Health", hint: "Body and mind", tone: "mint" },
  finance: { label: "Finance", hint: "Money without the circus", tone: "mint" },
  shopping: { label: "Shopping", hint: "Buy and sell", tone: "coral" },
  news: { label: "News", hint: "What happened", tone: "slate" },
  travel: { label: "Travel", hint: "Get there", tone: "sky" },
  maps: { label: "Maps", hint: "Where things are", tone: "teal" },
  food: { label: "Food", hint: "Eat well", tone: "amber" },
  weather: { label: "Weather", hint: "Look up", tone: "sky" },
  business: { label: "Business", hint: "Work tools", tone: "slate" },
  lifestyle: { label: "Lifestyle", hint: "Daily texture", tone: "indigo" },
  kids: { label: "Kids", hint: "Small humans", tone: "amber" },
  video: { label: "Video", hint: "Moving pictures", tone: "coral" },
  communication: { label: "Communication", hint: "Talk it out", tone: "sky" },
  personalization: { label: "Personalization", hint: "Make it yours", tone: "rose" },
  libraries: { label: "Libraries", hint: "Reference", tone: "teal" },
  "coming-soon": { label: "Coming soon", hint: "Not live yet", tone: "amber" },
};

export const TONE_BG: Record<string, string> = {
  sky: "bg-cat-sky",
  mint: "bg-cat-mint",
  coral: "bg-cat-coral",
  rose: "bg-cat-rose",
  teal: "bg-cat-teal",
  amber: "bg-cat-amber",
  indigo: "bg-cat-indigo",
  slate: "bg-cat-slate",
};

function iconFromUrl(url?: string) {
  if (!url || url === "#" || !url.startsWith("http")) return undefined;
  try {
    const host = new URL(url).hostname.replace(/^www\./, "");
    return `https://www.google.com/s2/favicons?sz=128&domain=${host}`;
  } catch {
    return undefined;
  }
}

function app(
  partial: Omit<AppEntry, "rating" | "ratingsCount" | "description"> & {
    rating?: number;
    ratingsCount?: number;
    description?: string;
  },
): AppEntry {
  const merged = {
    rating: 4.5,
    ratingsCount: 128,
    description: partial.tagline,
    platform: "Unknown",
    ...partial,
    iconUrl: partial.iconUrl || iconFromUrl(partial.url),
  };
  return {
    ...merged,
    provenance: inferProvenance(merged),
    roles: inferRoles(merged),
  };
}

export const SEED: AppEntry[] = [
  app({
    id: "photopea",
    name: "Photopea",
    tagline: "Serious photo editing that lives in a tab.",
    description:
      "Layers, PSD files, and a toolbar you already know — without a 4GB installer. A PWA that treats the browser like a studio.",
    url: "https://www.photopea.com/",
    developer: "Photopea",
    genres: ["photo", "tools", "productivity"],
    installable: true,
    featured: true,
    editorsPick: true,
    sponsored: true,
    rating: 4.9,
    ratingsCount: 18420,
    source: "Public",
  }),
  app({
    id: "excalidraw",
    name: "Excalidraw",
    tagline: "Whiteboard with handwriting energy.",
    description:
      "Sketch diagrams that look human. Collaborate live. Install it and keep drawing on a plane.",
    url: "https://excalidraw.com/",
    developer: "Excalidraw",
    genres: ["productivity", "tools"],
    installable: true,
    featured: true,
    rating: 4.7,
    ratingsCount: 9320,
    source: "Public",
  }),
  app({
    id: "drawio",
    name: "draw.io",
    tagline: "Diagrams that survive airplane mode.",
    url: "https://app.diagrams.net/",
    developer: "JGraph",
    genres: ["productivity", "business", "tools"],
    offline: true,
    installable: true,
    rating: 4.8,
    ratingsCount: 22100,
    source: "Public",
  }),
  app({
    id: "squoosh",
    name: "Squoosh",
    tagline: "Shrink images on your device. Nobody else sees them.",
    url: "https://squoosh.app/",
    developer: "Google Chrome Labs",
    genres: ["photo", "tools"],
    offline: true,
    installable: true,
    editorsPick: true,
    rating: 4.8,
    ratingsCount: 5400,
    source: "Public",
  }),
  app({
    id: "svgomg",
    name: "SVGOMG",
    tagline: "SVG cleanup with a live preview.",
    url: "https://jakearchibald.github.io/svgomg/",
    developer: "Jake Archibald",
    genres: ["tools", "photo"],
    installable: true,
    rating: 4.5,
    ratingsCount: 2104,
    source: "Public",
  }),
  app({
    id: "pwa-directory",
    name: "PWA Directory",
    tagline: "Evidence-checked installable web apps.",
    url: "https://pwa.directory/",
    developer: "PWA Directory",
    genres: ["libraries", "tools"],
    offline: true,
    installable: true,
    rating: 4.6,
    ratingsCount: 880,
    source: "Public",
  }),
  app({
    id: "appbird",
    name: "appBird",
    tagline: "A roost for small AI-built web apps.",
    url: "https://appbird.store/",
    developer: "appBird",
    genres: ["libraries", "tools"],
    installable: true,
    aiBuilt: true,
    rating: 4.3,
    ratingsCount: 410,
    source: "Public",
  }),
  app({
    id: "builderfest-kevin",
    name: "Builder Fest (Kevin O’Leary × Emergent)",
    tagline: "A $100K contest gallery of vibe-coded business apps. Do not lose this URL.",
    description:
      "Emergent’s public showcase for the Kevin O’Leary Builder Fest. Thousands of live entries — no-code / agent-built web apps, each with its own page. This is a goldmine for Appendix: amateur and pro PWAs in the wild, already tagged by a builder platform. Remember: https://app.emergent.sh/showcase/builderfest-kevin",
    url: "https://app.emergent.sh/showcase/builderfest-kevin",
    developer: "Emergent × Kevin O’Leary",
    genres: ["libraries", "business", "tools"],
    installable: false,
    aiBuilt: true,
    featured: true,
    editorsPick: true,
    rating: 4.6,
    ratingsCount: 3431,
    source: "Remembered",
    platform: "Emergent",
  }),
  app({
    id: "emergent",
    name: "Emergent",
    tagline: "Chat with agents. They design, code, and deploy.",
    url: "https://app.emergent.sh/",
    developer: "Emergent Labs",
    genres: ["tools", "productivity", "business"],
    aiBuilt: true,
    featured: true,
    rating: 4.5,
    ratingsCount: 1200,
    source: "Remembered",
    platform: "Emergent",
  }),
  app({
    id: "karaokedokie",
    name: "KaraokeDokie",
    tagline: "Type a song. Get a performance pack.",
    description:
      "Visual-first karaoke kits for people who treat a living room like a venue. Coming soon — file your interest.",
    url: "#",
    developer: "ZAF Recordz",
    genres: ["music", "entertainment", "coming-soon"],
    aiBuilt: true,
    featured: true,
    comingSoon: true,
    editorsPick: true,
    rating: 4.8,
    ratingsCount: 96,
    source: "ZAF",
    platform: "Grok",
    roles: ["singers", "band", "session"],
  }),
  app({
    id: "noteworthy",
    name: "Noteworthy",
    tagline: "A spatial notepad for thoughts that refuse a list.",
    url: "#",
    developer: "ZAF Labs",
    genres: ["productivity", "lifestyle", "coming-soon"],
    aiBuilt: true,
    featured: true,
    comingSoon: true,
    rating: 4.7,
    ratingsCount: 54,
    source: "ZAF",
    platform: "Grok",
  }),
  app({
    id: "preset-irl",
    name: "PRESET//IRL",
    tagline: "Save setups for gear that has no Save button.",
    url: "#",
    developer: "ZAF Labs",
    genres: ["music", "tools", "coming-soon"],
    featured: true,
    comingSoon: true,
    sponsored: true,
    rating: 4.6,
    ratingsCount: 33,
    source: "ZAF",
    platform: "Grok",
  }),
  app({
    id: "identity-studioz",
    name: "Identity StudioZ",
    tagline: "Stage names, glyphs, compatibility scores.",
    url: "#",
    developer: "ZAF Labs",
    genres: ["personalization", "tools", "coming-soon"],
    aiBuilt: true,
    comingSoon: true,
    rating: 4.5,
    ratingsCount: 21,
    source: "ZAF",
    platform: "Grok",
  }),
  app({
    id: "literalizer",
    name: "The Literalizer",
    tagline: "Jargon in. Human out. Landmines labeled.",
    url: "#",
    developer: "ZAF Labs",
    genres: ["productivity", "education", "coming-soon"],
    aiBuilt: true,
    comingSoon: true,
    rating: 4.4,
    ratingsCount: 18,
    source: "ZAF",
    platform: "Grok",
  }),
  app({
    id: "last-place",
    name: "Last Place",
    tagline: "Photo the spot so future-you can find it.",
    url: "#",
    developer: "Opportunity Co",
    genres: ["maps", "tools", "coming-soon"],
    comingSoon: true,
    rating: 4.3,
    ratingsCount: 12,
    source: "Dossier",
  }),
  app({
    id: "did-i-lock",
    name: "Did I Lock It?",
    tagline: "One tap. Timestamp. Close the loop.",
    url: "#",
    developer: "Opportunity Co",
    genres: ["lifestyle", "tools", "coming-soon"],
    comingSoon: true,
    rating: 4.5,
    ratingsCount: 40,
    source: "Dossier",
  }),
  app({
    id: "hextris",
    name: "Hextris",
    tagline: "Hexagon stacking. Extremely stealable lunch break.",
    url: "https://hextris.io/",
    developer: "Hextris",
    genres: ["games"],
    installable: true,
    rating: 4.6,
    ratingsCount: 3100,
    source: "Public",
  }),
  app({
    id: "play2048",
    name: "2048",
    tagline: "The tile game that ate a year of productivity.",
    url: "https://play2048.co/",
    developer: "Gabriele Cirulli",
    genres: ["games"],
    installable: true,
    rating: 4.7,
    ratingsCount: 12040,
    source: "Public",
  }),
  app({
    id: "proxx",
    name: "PROXX",
    tagline: "Minesweeper that respects your CPU.",
    url: "https://proxx.app/",
    developer: "Google Chrome Labs",
    genres: ["games"],
    installable: true,
    rating: 4.5,
    ratingsCount: 890,
    source: "Public",
  }),
  app({
    id: "devdocs",
    name: "DevDocs",
    tagline: "API docs that work on a train.",
    url: "https://devdocs.io/",
    developer: "DevDocs",
    genres: ["education", "libraries", "productivity"],
    installable: true,
    offline: true,
    rating: 4.8,
    ratingsCount: 6700,
    source: "Public",
  }),
  app({
    id: "vscode-web",
    name: "VS Code for the Web",
    tagline: "The editor, minus the installer ritual.",
    url: "https://vscode.dev/",
    developer: "Microsoft",
    genres: ["productivity", "tools", "business"],
    rating: 4.6,
    ratingsCount: 15400,
    source: "Public",
  }),
  app({
    id: "appendix-self",
    name: "Appendix",
    tagline: "This store. The extra organ the web grew anyway.",
    description:
      "A catalog of progressive web apps. No APK, no 30% haircut, no ‘download now’ trap. You open a link. If it is good, you keep it.",
    url: "/",
    developer: "Appendix",
    genres: ["libraries", "tools"],
    installable: true,
    aiBuilt: true,
    featured: true,
    editorsPick: true,
    rating: 5,
    ratingsCount: 1,
    source: "This build",
    platform: "Grok",
  }),
  app({
    id: "proton-mail",
    name: "Proton Mail",
    tagline: "Encrypted mail that does not live in a store.",
    url: "https://mail.proton.me/",
    developer: "Proton",
    genres: ["communication", "productivity"],
    installable: true,
    featured: true,
    rating: 4.7,
    ratingsCount: 42000,
    source: "Public",
  }),
  app({
    id: "stackblitz",
    name: "StackBlitz",
    tagline: "A full IDE in the tab. Native never offered this.",
    url: "https://stackblitz.com/",
    developer: "StackBlitz",
    genres: ["tools", "productivity", "education"],
    installable: true,
    editorsPick: true,
    rating: 4.8,
    ratingsCount: 9100,
    source: "Public",
  }),
  app({
    id: "figma",
    name: "Figma",
    tagline: "Design in the browser. The store copy is a souvenir.",
    url: "https://www.figma.com/",
    developer: "Figma",
    genres: ["photo", "productivity", "business"],
    rating: 4.8,
    ratingsCount: 88000,
    source: "Public",
  }),
  app({
    id: "pinterest",
    name: "Pinterest",
    tagline: "Moodboards without the 90MB APK.",
    url: "https://www.pinterest.com/",
    developer: "Pinterest",
    genres: ["social", "lifestyle", "photo"],
    installable: true,
    rating: 4.4,
    ratingsCount: 120000,
    source: "Public",
  }),
  app({
    id: "lichess",
    name: "Lichess",
    tagline: "Chess. Free. No store tax on your opening book.",
    url: "https://lichess.org/",
    developer: "Lichess",
    genres: ["games", "education"],
    installable: true,
    rating: 4.9,
    ratingsCount: 54000,
    source: "Public",
  }),
  app({
    id: "penpot",
    name: "Penpot",
    tagline: "Open-source design tool. Installable.",
    url: "https://design.penpot.app/",
    developer: "Penpot",
    genres: ["photo", "tools", "productivity"],
    installable: true,
    rating: 4.6,
    ratingsCount: 2100,
    source: "Public",
  }),
  app({
    id: "affine",
    name: "AFFiNE",
    tagline: "Notes, whiteboard, docs. One local-first surface.",
    url: "https://app.affine.pro/",
    developer: "AFFiNE",
    genres: ["productivity", "tools"],
    installable: true,
    rating: 4.5,
    ratingsCount: 1800,
    source: "Public",
  }),
  app({
    id: "telegram-web",
    name: "Telegram Web",
    tagline: "The chat client, as a URL.",
    url: "https://web.telegram.org/",
    developer: "Telegram",
    genres: ["communication", "social"],
    rating: 4.6,
    ratingsCount: 67000,
    source: "Public",
  }),
  app({
    id: "starbucks",
    name: "Starbucks",
    tagline: "Order coffee without renting space on a home screen via Apple.",
    url: "https://www.starbucks.com/",
    developer: "Starbucks",
    genres: ["food", "shopping"],
    installable: true,
    rating: 4.3,
    ratingsCount: 31000,
    source: "Public",
  }),
  app({
    id: "openrouter",
    name: "OpenRouter",
    tagline: "One door to many models.",
    url: "https://openrouter.ai/",
    developer: "OpenRouter",
    genres: ["tools", "productivity"],
    rating: 4.5,
    ratingsCount: 2400,
    source: "Public",
  }),
  app({
    id: "taskade",
    name: "Taskade",
    tagline: "Tasks, notes, and agents in one tab.",
    url: "https://www.taskade.com/",
    developer: "Taskade",
    genres: ["productivity", "business"],
    installable: true,
    rating: 4.4,
    ratingsCount: 5200,
    source: "Public",
  }),
  app({
    id: "1inch",
    name: "1inch",
    tagline: "DeFi aggregator as an installable web app.",
    url: "https://app.1inch.io/",
    developer: "1inch",
    genres: ["finance"],
    rating: 4.2,
    ratingsCount: 3900,
    source: "Public",
  }),
  app({
    id: "tinder",
    name: "Tinder",
    tagline: "The native app was never the only door.",
    url: "https://tinder.com/",
    developer: "Tinder",
    genres: ["social", "lifestyle"],
    rating: 3.9,
    ratingsCount: 210000,
    source: "Public",
  }),
  app({
    id: "xbox-cloud",
    name: "Xbox Cloud Gaming",
    tagline: "Console as a tab. The store still wants a cut of the rest.",
    url: "https://www.xbox.com/play",
    developer: "Microsoft",
    genres: ["games", "entertainment"],
    rating: 4.3,
    ratingsCount: 18000,
    source: "Public",
  }),
  app({
    id: "spotify",
    name: "Spotify",
    tagline: "The web player that made the APK optional.",
    url: "https://open.spotify.com/",
    developer: "Spotify",
    genres: ["music", "entertainment"],
    rating: 4.5,
    ratingsCount: 250000,
    source: "Public",
  }),
  app({
    id: "whatsapp-web",
    name: "WhatsApp",
    tagline: "The chat you already have, as a tab.",
    url: "https://web.whatsapp.com/",
    developer: "Meta",
    genres: ["communication", "social"],
    rating: 4.4,
    ratingsCount: 410000,
  }),
  app({
    id: "gmail",
    name: "Gmail",
    tagline: "Mail without the Play Store handshake.",
    url: "https://mail.google.com/",
    developer: "Google",
    genres: ["communication", "productivity"],
    rating: 4.5,
    ratingsCount: 900000,
  }),
  app({
    id: "google-maps",
    name: "Google Maps",
    tagline: "The map that never needed an APK.",
    url: "https://maps.google.com/",
    developer: "Google",
    genres: ["maps", "travel"],
    rating: 4.6,
    ratingsCount: 800000,
  }),
  app({
    id: "youtube",
    name: "YouTube",
    tagline: "Video. Browser-native. Obviously.",
    url: "https://www.youtube.com/",
    developer: "Google",
    genres: ["video", "entertainment"],
    rating: 4.5,
    ratingsCount: 1200000,
  }),
  app({
    id: "chatgpt",
    name: "ChatGPT",
    tagline: "The tab everyone already installed in their head.",
    url: "https://chatgpt.com/",
    developer: "OpenAI",
    genres: ["productivity", "education", "tools"],
    rating: 4.7,
    ratingsCount: 620000,
    featured: true,
  }),
  app({
    id: "grok",
    name: "Grok",
    tagline: "xAI in a tab. We would say that.",
    url: "https://grok.com/",
    developer: "xAI",
    genres: ["productivity", "tools"],
    rating: 4.6,
    ratingsCount: 48000,
    featured: true,
    platform: "Grok",
    sponsored: true,
  }),
  app({
    id: "claude",
    name: "Claude",
    tagline: "A long conversation that lives in the browser.",
    url: "https://claude.ai/",
    developer: "Anthropic",
    genres: ["productivity", "education"],
    rating: 4.6,
    ratingsCount: 91000,
  }),
  app({
    id: "gemini",
    name: "Gemini",
    tagline: "Google’s model, minus the store listing.",
    url: "https://gemini.google.com/",
    developer: "Google",
    genres: ["productivity", "tools"],
    rating: 4.4,
    ratingsCount: 110000,
  }),
  app({
    id: "perplexity",
    name: "Perplexity",
    tagline: "Search that answers, then cites.",
    url: "https://www.perplexity.ai/",
    developer: "Perplexity",
    genres: ["education", "tools", "news"],
    rating: 4.5,
    ratingsCount: 54000,
  }),
  app({
    id: "notion",
    name: "Notion",
    tagline: "Docs, wikis, and the second brain as a URL.",
    url: "https://www.notion.so/",
    developer: "Notion",
    genres: ["productivity", "business"],
    rating: 4.6,
    ratingsCount: 210000,
  }),
  app({
    id: "canva",
    name: "Canva",
    tagline: "Layout in the browser. The poster is already done.",
    url: "https://www.canva.com/",
    developer: "Canva",
    genres: ["photo", "productivity", "business"],
    rating: 4.7,
    ratingsCount: 340000,
    sponsored: true,
  }),
  app({
    id: "github-dev",
    name: "github.dev",
    tagline: "Press . on any repo. You’re in an editor.",
    url: "https://github.dev/",
    developer: "GitHub",
    genres: ["tools", "productivity", "education"],
    rating: 4.6,
    ratingsCount: 28000,
  }),
  app({
    id: "codesandbox",
    name: "CodeSandbox",
    tagline: "A running app inside the URL bar.",
    url: "https://codesandbox.io/",
    developer: "CodeSandbox",
    genres: ["tools", "education"],
    rating: 4.5,
    ratingsCount: 41000,
  }),
  app({
    id: "codepen",
    name: "CodePen",
    tagline: "Front-end sketches. Share the tab.",
    url: "https://codepen.io/",
    developer: "CodePen",
    genres: ["tools", "education", "photo"],
    rating: 4.6,
    ratingsCount: 67000,
  }),
  app({
    id: "duolingo",
    name: "Duolingo",
    tagline: "Streaks without the store.",
    url: "https://www.duolingo.com/",
    developer: "Duolingo",
    genres: ["education", "kids"],
    rating: 4.7,
    ratingsCount: 510000,
  }),
  app({
    id: "khan",
    name: "Khan Academy",
    tagline: "School that fits in a bookmark.",
    url: "https://www.khanacademy.org/",
    developer: "Khan Academy",
    genres: ["education", "kids"],
    rating: 4.8,
    ratingsCount: 120000,
  }),
  app({
    id: "wikipedia",
    name: "Wikipedia",
    tagline: "The original progressive web everything.",
    url: "https://www.wikipedia.org/",
    developer: "Wikimedia",
    genres: ["education", "libraries", "news"],
    rating: 4.8,
    ratingsCount: 980000,
  }),
  app({
    id: "archive",
    name: "Internet Archive",
    tagline: "The web, kept.",
    url: "https://archive.org/",
    developer: "Internet Archive",
    genres: ["libraries", "education", "video"],
    rating: 4.7,
    ratingsCount: 88000,
  }),
  app({
    id: "hacker-news",
    name: "Hacker News",
    tagline: "Orange links. Still a tab.",
    url: "https://news.ycombinator.com/",
    developer: "Y Combinator",
    genres: ["news", "business"],
    rating: 4.4,
    ratingsCount: 72000,
  }),
  app({
    id: "reddit",
    name: "Reddit",
    tagline: "Forums that learned to be an app.",
    url: "https://www.reddit.com/",
    developer: "Reddit",
    genres: ["social", "news"],
    rating: 4.2,
    ratingsCount: 640000,
  }),
  app({
    id: "bsky",
    name: "Bluesky",
    tagline: "A timeline you can install.",
    url: "https://bsky.app/",
    developer: "Bluesky",
    genres: ["social", "communication"],
    installable: true,
    rating: 4.3,
    ratingsCount: 39000,
  }),
  app({
    id: "discord",
    name: "Discord",
    tagline: "Servers in the browser.",
    url: "https://discord.com/app",
    developer: "Discord",
    genres: ["communication", "social", "games"],
    rating: 4.4,
    ratingsCount: 430000,
  }),
  app({
    id: "twitch",
    name: "Twitch",
    tagline: "Live video. No store required.",
    url: "https://www.twitch.tv/",
    developer: "Twitch",
    genres: ["video", "entertainment", "games"],
    rating: 4.4,
    ratingsCount: 290000,
  }),
  app({
    id: "netflix",
    name: "Netflix",
    tagline: "The app that proved the browser was enough.",
    url: "https://www.netflix.com/",
    developer: "Netflix",
    genres: ["video", "entertainment"],
    rating: 4.5,
    ratingsCount: 1100000,
  }),
  app({
    id: "tradingview",
    name: "TradingView",
    tagline: "Charts that ate the desktop.",
    url: "https://www.tradingview.com/",
    developer: "TradingView",
    genres: ["finance", "business"],
    rating: 4.7,
    ratingsCount: 150000,
  }),
  app({
    id: "coinbase",
    name: "Coinbase",
    tagline: "A wallet that starts as a URL.",
    url: "https://www.coinbase.com/",
    developer: "Coinbase",
    genres: ["finance"],
    rating: 4.1,
    ratingsCount: 98000,
  }),
  app({
    id: "airbnb",
    name: "Airbnb",
    tagline: "Stay somewhere. Book in the tab.",
    url: "https://www.airbnb.com/",
    developer: "Airbnb",
    genres: ["travel", "shopping"],
    rating: 4.4,
    ratingsCount: 310000,
  }),
  app({
    id: "uber",
    name: "Uber",
    tagline: "A ride without installing a second icon.",
    url: "https://www.uber.com/",
    developer: "Uber",
    genres: ["travel", "maps"],
    rating: 4.3,
    ratingsCount: 270000,
  }),
  app({
    id: "weather-com",
    name: "Weather",
    tagline: "Look up. Then look at the tab.",
    url: "https://weather.com/",
    developer: "The Weather Channel",
    genres: ["weather"],
    rating: 4.3,
    ratingsCount: 88000,
  }),
  app({
    id: "strava",
    name: "Strava",
    tagline: "Miles, logged in the browser.",
    url: "https://www.strava.com/",
    developer: "Strava",
    genres: ["health"],
    rating: 4.5,
    ratingsCount: 140000,
  }),
  app({
    id: "desmos",
    name: "Desmos",
    tagline: "Graphing calculator. No TI tax.",
    url: "https://www.desmos.com/calculator",
    developer: "Desmos",
    genres: ["education", "tools"],
    rating: 4.9,
    ratingsCount: 76000,
    editorsPick: true,
  }),
  app({
    id: "pomofocus",
    name: "Pomofocus",
    tagline: "A timer with opinions.",
    url: "https://pomofocus.io/",
    developer: "Pomofocus",
    genres: ["productivity", "tools"],
    installable: true,
    rating: 4.6,
    ratingsCount: 12000,
  }),
  app({
    id: "webamp",
    name: "Webamp",
    tagline: "Winamp, resurrected as a PWA-shaped ghost.",
    url: "https://webamp.org/",
    developer: "Jordan Eldredge",
    genres: ["music", "entertainment"],
    rating: 4.8,
    ratingsCount: 19000,
    editorsPick: true,
  }),
  app({
    id: "chess-com",
    name: "Chess.com",
    tagline: "The other chess tab.",
    url: "https://www.chess.com/",
    developer: "Chess.com",
    genres: ["games", "education"],
    rating: 4.6,
    ratingsCount: 220000,
  }),
  app({
    id: "krunker",
    name: "Krunker",
    tagline: "FPS in a tab. Native never saw it coming.",
    url: "https://krunker.io/",
    developer: "Krunker",
    genres: ["games"],
    rating: 4.4,
    ratingsCount: 67000,
  }),
  app({
    id: "poki",
    name: "Poki",
    tagline: "A whole arcade. Instant.",
    url: "https://poki.com/",
    developer: "Poki",
    genres: ["games", "kids"],
    rating: 4.3,
    ratingsCount: 54000,
  }),
  app({
    id: "translate",
    name: "Google Translate",
    tagline: "Say it in the other language.",
    url: "https://translate.google.com/",
    developer: "Google",
    genres: ["education", "tools", "communication"],
    rating: 4.7,
    ratingsCount: 430000,
  }),
  app({
    id: "deepL",
    name: "DeepL",
    tagline: "Translation with a quieter tone of voice.",
    url: "https://www.deepl.com/translator",
    developer: "DeepL",
    genres: ["education", "tools"],
    rating: 4.8,
    ratingsCount: 61000,
  }),
  app({
    id: "imdb",
    name: "IMDb",
    tagline: "Credits, ratings, the list you already keep.",
    url: "https://www.imdb.com/",
    developer: "IMDb",
    genres: ["entertainment", "video"],
    rating: 4.4,
    ratingsCount: 180000,
  }),
  app({
    id: "letterboxd",
    name: "Letterboxd",
    tagline: "A diary for people who watch things.",
    url: "https://letterboxd.com/",
    developer: "Letterboxd",
    genres: ["entertainment", "social", "video"],
    rating: 4.7,
    ratingsCount: 52000,
  }),
  app({
    id: "amazon",
    name: "Amazon",
    tagline: "The store that made stores nervous.",
    url: "https://www.amazon.com/",
    developer: "Amazon",
    genres: ["shopping"],
    rating: 4.2,
    ratingsCount: 900000,
  }),
  app({
    id: "etsy",
    name: "Etsy",
    tagline: "Handmade, shipped from a tab.",
    url: "https://www.etsy.com/",
    developer: "Etsy",
    genres: ["shopping", "lifestyle"],
    rating: 4.4,
    ratingsCount: 160000,
  }),
  app({
    id: "bandlab",
    name: "BandLab",
    tagline: "A DAW that does not ask for an installer.",
    url: "https://www.bandlab.com/",
    developer: "BandLab",
    genres: ["music", "tools"],
    rating: 4.5,
    ratingsCount: 43000,
  }),
  app({
    id: "capcut",
    name: "CapCut",
    tagline: "Cuts in the browser.",
    url: "https://www.capcut.com/",
    developer: "CapCut",
    genres: ["video", "tools"],
    rating: 4.4,
    ratingsCount: 210000,
  }),
  app({
    id: "remove-bg",
    name: "remove.bg",
    tagline: "The background leaves.",
    url: "https://www.remove.bg/",
    developer: "Kaleido",
    genres: ["photo", "tools"],
    rating: 4.6,
    ratingsCount: 39000,
  }),
  app({
    id: "x-com",
    name: "X",
    tagline: "The timeline as a tab.",
    url: "https://x.com/",
    developer: "X",
    genres: ["social", "news", "communication"],
    rating: 4.1,
    ratingsCount: 820000,
  }),
  app({
    id: "instagram",
    name: "Instagram",
    tagline: "Photos that already lived in the browser.",
    url: "https://www.instagram.com/",
    developer: "Meta",
    genres: ["social", "photo"],
    rating: 4.3,
    ratingsCount: 980000,
  }),
  app({
    id: "tiktok",
    name: "TikTok",
    tagline: "Short video. Long scroll.",
    url: "https://www.tiktok.com/",
    developer: "TikTok",
    genres: ["social", "video", "entertainment"],
    rating: 4.4,
    ratingsCount: 1100000,
  }),
  app({
    id: "linkedin",
    name: "LinkedIn",
    tagline: "The resume that never logs off.",
    url: "https://www.linkedin.com/",
    developer: "LinkedIn",
    genres: ["business", "social"],
    rating: 4.2,
    ratingsCount: 410000,
  }),
  app({
    id: "threads",
    name: "Threads",
    tagline: "A shorter timeline, same family.",
    url: "https://www.threads.com/",
    developer: "Meta",
    genres: ["social", "communication"],
    rating: 4.0,
    ratingsCount: 76000,
  }),
  app({
    id: "google-calendar",
    name: "Google Calendar",
    tagline: "The week, as a URL.",
    url: "https://calendar.google.com/",
    developer: "Google",
    genres: ["productivity", "business"],
    rating: 4.6,
    ratingsCount: 520000,
  }),
  app({
    id: "google-drive",
    name: "Google Drive",
    tagline: "Files that never needed a disk.",
    url: "https://drive.google.com/",
    developer: "Google",
    genres: ["productivity", "tools"],
    rating: 4.6,
    ratingsCount: 710000,
  }),
  app({
    id: "google-docs",
    name: "Google Docs",
    tagline: "The document is the tab.",
    url: "https://docs.google.com/",
    developer: "Google",
    genres: ["productivity", "education", "business"],
    rating: 4.7,
    ratingsCount: 880000,
  }),
  app({
    id: "sheets",
    name: "Google Sheets",
    tagline: "A spreadsheet that shares itself.",
    url: "https://sheets.google.com/",
    developer: "Google",
    genres: ["productivity", "business", "finance"],
    rating: 4.6,
    ratingsCount: 430000,
  }),
  app({
    id: "slack",
    name: "Slack",
    tagline: "Work chat, no installer sermon.",
    url: "https://app.slack.com/",
    developer: "Slack",
    genres: ["communication", "business"],
    rating: 4.4,
    ratingsCount: 290000,
  }),
  app({
    id: "zoom",
    name: "Zoom",
    tagline: "The meeting that starts in a tab.",
    url: "https://zoom.us/",
    developer: "Zoom",
    genres: ["communication", "business", "video"],
    rating: 4.3,
    ratingsCount: 540000,
  }),
  app({
    id: "trello",
    name: "Trello",
    tagline: "Boards. Cards. Done-ish.",
    url: "https://trello.com/",
    developer: "Atlassian",
    genres: ["productivity", "business"],
    rating: 4.5,
    ratingsCount: 180000,
  }),
  app({
    id: "asana",
    name: "Asana",
    tagline: "Tasks with a nicer spine.",
    url: "https://app.asana.com/",
    developer: "Asana",
    genres: ["productivity", "business"],
    rating: 4.4,
    ratingsCount: 96000,
  }),
  app({
    id: "linear",
    name: "Linear",
    tagline: "Issue tracking that respects a keyboard.",
    url: "https://linear.app/",
    developer: "Linear",
    genres: ["productivity", "tools", "business"],
    rating: 4.8,
    ratingsCount: 21000,
    editorsPick: true,
    sponsored: true,
  }),
  app({
    id: "miro",
    name: "Miro",
    tagline: "A whiteboard the size of a wall.",
    url: "https://miro.com/",
    developer: "Miro",
    genres: ["productivity", "business", "education"],
    rating: 4.5,
    ratingsCount: 74000,
  }),
  app({
    id: "replit",
    name: "Replit",
    tagline: "Run the code where you wrote it.",
    url: "https://replit.com/",
    developer: "Replit",
    genres: ["tools", "education"],
    rating: 4.6,
    ratingsCount: 88000,
    featured: true,
  }),
  app({
    id: "huggingface",
    name: "Hugging Face",
    tagline: "Models, spaces, the public square for weights.",
    url: "https://huggingface.co/",
    developer: "Hugging Face",
    genres: ["tools", "education"],
    rating: 4.7,
    ratingsCount: 54000,
  }),
  app({
    id: "colab",
    name: "Google Colab",
    tagline: "Notebooks with a free GPU rumor.",
    url: "https://colab.research.google.com/",
    developer: "Google",
    genres: ["education", "tools"],
    rating: 4.7,
    ratingsCount: 120000,
  }),
  app({
    id: "kaggle",
    name: "Kaggle",
    tagline: "Data contests in a browser.",
    url: "https://www.kaggle.com/",
    developer: "Google",
    genres: ["education", "tools"],
    rating: 4.6,
    ratingsCount: 67000,
  }),
  app({
    id: "scratch",
    name: "Scratch",
    tagline: "Kids snap blocks. A game appears.",
    url: "https://scratch.mit.edu/",
    developer: "MIT",
    genres: ["kids", "education", "games"],
    rating: 4.8,
    ratingsCount: 210000,
    editorsPick: true,
  }),
  app({
    id: "code-org",
    name: "Code.org",
    tagline: "Hour of Code, every hour.",
    url: "https://code.org/",
    developer: "Code.org",
    genres: ["kids", "education"],
    rating: 4.7,
    ratingsCount: 54000,
  }),
  app({
    id: "pbs-kids",
    name: "PBS Kids",
    tagline: "Games that don’t yell at parents.",
    url: "https://pbskids.org/",
    developer: "PBS",
    genres: ["kids", "education", "games"],
    rating: 4.6,
    ratingsCount: 88000,
  }),
  app({
    id: "radio-garden",
    name: "Radio Garden",
    tagline: "Spin the globe. Land on a station.",
    url: "https://radio.garden/",
    developer: "Radio Garden",
    genres: ["music", "entertainment"],
    rating: 4.8,
    ratingsCount: 31000,
    editorsPick: true,
  }),
  app({
    id: "soundcloud",
    name: "SoundCloud",
    tagline: "The demo tape of the internet.",
    url: "https://soundcloud.com/",
    developer: "SoundCloud",
    genres: ["music"],
    rating: 4.4,
    ratingsCount: 190000,
  }),
  app({
    id: "bandcamp",
    name: "Bandcamp",
    tagline: "Pay the artist. Get the files.",
    url: "https://bandcamp.com/",
    developer: "Bandcamp",
    genres: ["music", "shopping"],
    rating: 4.8,
    ratingsCount: 72000,
  }),
  app({
    id: "youtube-music",
    name: "YouTube Music",
    tagline: "The other Spotify, already in Chrome.",
    url: "https://music.youtube.com/",
    developer: "Google",
    genres: ["music"],
    rating: 4.4,
    ratingsCount: 260000,
  }),
  app({
    id: "nytimes",
    name: "The New York Times",
    tagline: "The paper that learned HTML.",
    url: "https://www.nytimes.com/",
    developer: "The New York Times",
    genres: ["news"],
    rating: 4.5,
    ratingsCount: 310000,
  }),
  app({
    id: "bbc",
    name: "BBC",
    tagline: "World service, browser service.",
    url: "https://www.bbc.com/",
    developer: "BBC",
    genres: ["news", "video"],
    rating: 4.6,
    ratingsCount: 240000,
  }),
  app({
    id: "npr",
    name: "NPR",
    tagline: "Radio you can read.",
    url: "https://www.npr.org/",
    developer: "NPR",
    genres: ["news", "music"],
    rating: 4.6,
    ratingsCount: 98000,
  }),
  app({
    id: "medium",
    name: "Medium",
    tagline: "Essays with a clap count.",
    url: "https://medium.com/",
    developer: "Medium",
    genres: ["news", "education"],
    rating: 4.2,
    ratingsCount: 87000,
  }),
  app({
    id: "substack",
    name: "Substack",
    tagline: "Newsletters that grew a spine.",
    url: "https://substack.com/",
    developer: "Substack",
    genres: ["news", "social"],
    rating: 4.4,
    ratingsCount: 41000,
  }),
  app({
    id: "paypal",
    name: "PayPal",
    tagline: "Send it. Don’t narrate it.",
    url: "https://www.paypal.com/",
    developer: "PayPal",
    genres: ["finance"],
    rating: 4.3,
    ratingsCount: 420000,
  }),
  app({
    id: "cash-app",
    name: "Cash App",
    tagline: "The dollar sign in a tab.",
    url: "https://cash.app/",
    developer: "Block",
    genres: ["finance"],
    rating: 4.4,
    ratingsCount: 210000,
  }),
  app({
    id: "robinhood",
    name: "Robinhood",
    tagline: "Trades without a trading floor.",
    url: "https://robinhood.com/",
    developer: "Robinhood",
    genres: ["finance"],
    rating: 4.2,
    ratingsCount: 150000,
  }),
  app({
    id: "booking",
    name: "Booking.com",
    tagline: "A bed, somewhere.",
    url: "https://www.booking.com/",
    developer: "Booking.com",
    genres: ["travel", "shopping"],
    rating: 4.5,
    ratingsCount: 380000,
  }),
  app({
    id: "tripadvisor",
    name: "Tripadvisor",
    tagline: "Opinions about the soup.",
    url: "https://www.tripadvisor.com/",
    developer: "Tripadvisor",
    genres: ["travel", "food"],
    rating: 4.3,
    ratingsCount: 190000,
  }),
  app({
    id: "doordash",
    name: "DoorDash",
    tagline: "Dinner, dispatched.",
    url: "https://www.doordash.com/",
    developer: "DoorDash",
    genres: ["food", "shopping"],
    rating: 4.3,
    ratingsCount: 270000,
  }),
  app({
    id: "ikea",
    name: "IKEA",
    tagline: "Allen keys not included in the PWA.",
    url: "https://www.ikea.com/",
    developer: "IKEA",
    genres: ["shopping", "lifestyle"],
    rating: 4.4,
    ratingsCount: 160000,
  }),
  app({
    id: "alltrails",
    name: "AllTrails",
    tagline: "A hike with a battery.",
    url: "https://www.alltrails.com/",
    developer: "AllTrails",
    genres: ["travel", "health", "maps"],
    rating: 4.6,
    ratingsCount: 88000,
  }),
  app({
    id: "earth",
    name: "Google Earth",
    tagline: "The planet, zoomable.",
    url: "https://earth.google.com/",
    developer: "Google",
    genres: ["maps", "education", "travel"],
    rating: 4.7,
    ratingsCount: 140000,
    featured: true,
  }),
  app({
    id: "regex101",
    name: "Regex101",
    tagline: "The only regex that explains itself.",
    url: "https://regex101.com/",
    developer: "Regex101",
    genres: ["tools", "education"],
    rating: 4.9,
    ratingsCount: 18000,
    editorsPick: true,
  }),
  app({
    id: "mdn",
    name: "MDN Web Docs",
    tagline: "The manual the web actually uses.",
    url: "https://developer.mozilla.org/",
    developer: "Mozilla",
    genres: ["education", "tools", "libraries"],
    rating: 4.9,
    ratingsCount: 92000,
  }),
  app({
    id: "stackoverflow",
    name: "Stack Overflow",
    tagline: "Copy, paste, survive.",
    url: "https://stackoverflow.com/",
    developer: "Stack Overflow",
    genres: ["education", "tools"],
    rating: 4.6,
    ratingsCount: 410000,
  }),
  app({
    id: "leetcode",
    name: "LeetCode",
    tagline: "Interviews, gamified.",
    url: "https://leetcode.com/",
    developer: "LeetCode",
    genres: ["education", "games"],
    rating: 4.5,
    ratingsCount: 180000,
  }),
  app({
    id: "observable",
    name: "Observable",
    tagline: "Notebooks that draw.",
    url: "https://observablehq.com/",
    developer: "Observable",
    genres: ["tools", "education"],
    rating: 4.7,
    ratingsCount: 14000,
  }),
  app({
    id: "pixlr",
    name: "Pixlr",
    tagline: "The other photo tab.",
    url: "https://pixlr.com/",
    developer: "Pixlr",
    genres: ["photo", "tools"],
    rating: 4.4,
    ratingsCount: 67000,
  }),
  app({
    id: "grammarly",
    name: "Grammarly",
    tagline: "A quieter editor on your sentences.",
    url: "https://www.grammarly.com/",
    developer: "Grammarly",
    genres: ["productivity", "education"],
    rating: 4.5,
    ratingsCount: 230000,
  }),
  app({
    id: "dropbox",
    name: "Dropbox",
    tagline: "The folder that left the desktop.",
    url: "https://www.dropbox.com/",
    developer: "Dropbox",
    genres: ["productivity", "tools"],
    rating: 4.4,
    ratingsCount: 190000,
  }),
  app({
    id: "calendly",
    name: "Calendly",
    tagline: "Stop emailing times.",
    url: "https://calendly.com/",
    developer: "Calendly",
    genres: ["productivity", "business"],
    rating: 4.6,
    ratingsCount: 78000,
  }),
  app({
    id: "goodreads",
    name: "Goodreads",
    tagline: "The shelf you perform in public.",
    url: "https://www.goodreads.com/",
    developer: "Amazon",
    genres: ["libraries", "social", "education"],
    rating: 4.3,
    ratingsCount: 140000,
  }),
  ...MORE.map((m) =>
    app({
      id: m.id,
      name: m.name,
      url: m.url,
      developer: m.developer,
      tagline: m.tagline,
      genres: m.genres as Genre[],
    }),
  ),
];

export const GENRES = Object.keys(GENRE_META) as Genre[];

export const GENRES_ALPHA = GENRES.filter((g) => g !== "coming-soon").sort((a, b) =>
  GENRE_META[a].label.localeCompare(GENRE_META[b].label),
);

export const PLATFORM_GROUPS: { id: string; label: string; items: string[] }[] = [
  { id: "any", label: "Any builder", items: [] },
  { id: "unknown", label: "Unknown", items: ["Unknown"] },
  {
    id: "vibe",
    label: "AI builders",
    items: [
      "Grok",
      "Lovable",
      "Floot",
      "Bolt",
      "v0",
      "Replit",
      "Cursor",
      "Claude",
      "ChatGPT",
      "Gemini",
      "Copilot",
      "Base44",
      "Tempo",
      "Windsurf",
      "Softgen",
      "Create",
      "Dynamous",
      "Anything",
      "Rork",
      "Emergent",
      "Glide",
      "Bubble",
      "Adalo",
      "Softr",
      "CatDoes",
    ],
  },
  {
    id: "classic",
    label: "Classic web",
    items: [
      "Vanilla",
      "WordPress",
      "Webflow",
      "Framer",
      "A0",
      "GoDaddy",
      "Wix",
      "Squarespace",
      "Shopify",
      "Carrd",
    ],
  },
];

export const PLATFORMS = [...new Set(PLATFORM_GROUPS.flatMap((g) => g.items))];

export const AUDIENCES: { id: string; label: string; match: Genre[]; line: string }[] = [
  { id: "kids", label: "Kids", match: ["kids", "education"], line: "Small humans. Sticky screens." },
  { id: "gamers", label: "Gamers", match: ["games"], line: "No APK. Still a high score." },
  { id: "socialites", label: "Socialites", match: ["social", "communication"], line: "People, rooms, the feed." },
  { id: "nerds", label: "Nerds", match: ["productivity", "tools"], line: "A list, a timer, a second brain." },
  { id: "photographers", label: "Photographers", match: ["photo"], line: "Light, crop, lie a little." },
  { id: "musicians", label: "Musicians", match: ["music"], line: "Singers, engineers, the ones who make it." },
  { id: "listeners", label: "Music lovers", match: ["music"], line: "They don’t make it. They live in it." },
  { id: "cinephiles", label: "Cinephiles", match: ["entertainment", "video"], line: "Credits. Lists. Opinions." },
  { id: "teachers", label: "Teachers", match: ["education"], line: "The other side of the desk." },
  { id: "students", label: "Students", match: ["education", "libraries"], line: "Due at midnight. Started at 11." },
  { id: "health-nuts", label: "Health nuts", match: ["health"], line: "Steps, sleep, unsolicited advice." },
  { id: "monocles", label: "Old men with monocles", match: ["finance", "business"], line: "Money, but make it theatrical." },
  { id: "shoppers", label: "Shoppers", match: ["shopping"], line: "Carts that never empty." },
  { id: "junkies", label: "News junkies", match: ["news"], line: "Refresh. Refresh. Refresh." },
  { id: "wanderlust", label: "Wanderlust", match: ["travel"], line: "Weary, still going." },
  { id: "the-hungry", label: "The hungry", match: ["food"], line: "Dinner, dispatched." },
  { id: "umbrella", label: "Umbrella people", match: ["weather"], line: "Look up, then look at the tab." },
  { id: "devs", label: "Developers", match: ["tools", "productivity", "business"], line: "They built the yard. They browse it too." },
  { id: "stylists", label: "Mood-board people", match: ["lifestyle", "personalization"], line: "Taste, as a setting." },
  { id: "stack-rats", label: "Stack rats", match: ["libraries"], line: "Reference freaks. Quietly dangerous." },
  { id: "impatient", label: "The impatient", match: ["coming-soon"], line: "Coming soon. They hate that sentence." },
];

export const CROWD_SUBTYPES: Record<string, { id: string; label: string }[]> = {
  musicians: [
    { id: "singers", label: "Singers" },
    { id: "producers", label: "Producers" },
    { id: "djs", label: "DJs" },
    { id: "band", label: "Band members" },
    { id: "session", label: "Session players" },
  ],
  listeners: [
    { id: "listeners", label: "Listeners" },
    { id: "collectors", label: "Collectors" },
    { id: "radio", label: "Radio heads" },
    { id: "vinyl", label: "Vinyl" },
  ],
  gamers: [
    { id: "solo", label: "Solo" },
    { id: "couch", label: "Couch" },
    { id: "puzzle", label: "Puzzle" },
    { id: "idle", label: "Idle" },
    { id: "competitive", label: "Competitive" },
  ],
  photographers: [
    { id: "shooters", label: "Shooters" },
    { id: "editors", label: "Editors" },
    { id: "sharers", label: "Sharers" },
  ],
  devs: [
    { id: "weekend", label: "Weekend" },
    { id: "shipping", label: "Shipping" },
    { id: "docs", label: "Docs" },
  ],
  teachers: [
    { id: "classroom", label: "Classroom" },
    { id: "homeschool", label: "Homeschool" },
    { id: "tutors", label: "Tutors" },
  ],
  kids: [
    { id: "play", label: "Play" },
    { id: "learn", label: "Learn" },
    { id: "watch", label: "Watch" },
  ],
  shoppers: [
    { id: "browse", label: "Browse" },
    { id: "deal-hunt", label: "Deal-hunt" },
    { id: "lists", label: "Lists" },
  ],
  "health-nuts": [
    { id: "train", label: "Train" },
    { id: "track", label: "Track" },
    { id: "recover", label: "Recover" },
  ],
  cinephiles: [
    { id: "watch", label: "Watch" },
    { id: "log", label: "Log" },
    { id: "make", label: "Make" },
  ],
};

export function listingStatus(app: AppEntry): "live" | "dead" | "soon" {
  if (app.comingSoon) return "soon";
  if (!app.url || app.url === "#") return "dead";
  return "live";
}

export function isUp(app: AppEntry) {
  return listingStatus(app) === "live";
}

export function isLive(app: AppEntry) {
  return listingStatus(app) === "live";
}
