/** Forge dossier. Unknown stays unknown. cannot/weaknesses are load-bearing. */
export type FactoryKind = "amateur" | "pro" | "stitch" | "internal" | "lcap";

export type Factory = {
  id: string;
  name: string;
  url: string;
  category: string;
  can: string[];
  cannot: string[];
  strengths: string[];
  weaknesses: string[];
  pricing: string;
  auth: string;
  payments: string;
  scheduling: string;
  coupons: string;
  native: string;
  exports: string;
  hosting: string;
  skill: string;
  line: string;
  last_verified: string;
  provenance: FactoryKind;
  sponsored?: boolean;
  watch?: boolean;
};

function f(p: Factory): Factory {
  return p;
}

export const FACTORIES: Factory[] = [
  f({
    id: "Glide",
    name: "Glide",
    url: "https://www.glideapps.com/",
    category: "classic",
    can: ["website", "customer app", "employee app", "scheduling", "coupons", "service info", "spreadsheet backend", "no-login public screens"],
    cannot: ["native app store binary", "heavy custom game", "complex multi-tenant SSO"],
    strengths: ["amateur", "sheets-to-app", "fast internal + customer skins"],
    weaknesses: ["design ceiling", "logic gets cramped past mid-size"],
    pricing: "freemium / per-app plans",
    auth: "optional",
    payments: "unknown",
    scheduling: "yes",
    coupons: "yes via data",
    native: "PWA / wrappers, not true store binaries",
    exports: "limited",
    hosting: "Glide hosted",
    skill: "amateur",
    line: "A spreadsheet that grew an app around it.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "Softr",
    name: "Softr",
    url: "https://www.softr.io/",
    category: "classic",
    can: ["website", "customer app", "employee app", "client portals", "scheduling", "service info", "no-login public pages", "airtable"],
    cannot: ["native iOS binary", "realtime game"],
    strengths: ["amateur sites", "portals", "membership pages"],
    weaknesses: ["deep custom logic", "offline PWA"],
    pricing: "freemium",
    auth: "optional",
    payments: "yes",
    scheduling: "yes",
    coupons: "yes",
    native: "web",
    exports: "unknown",
    hosting: "Softr hosted",
    skill: "amateur",
    line: "Airtable in a coat. Public pages without a login wall.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "Bubble",
    name: "Bubble",
    url: "https://bubble.io/",
    category: "classic",
    can: ["website", "customer app", "employee app", "scheduling", "coupons", "payments", "workflows", "no-login public pages"],
    cannot: ["true native store binary without wrapper", "high-fidelity game"],
    strengths: ["full web app without code", "plugins", "two-sided products"],
    weaknesses: ["performance at scale", "vendor lock"],
    pricing: "subscription",
    auth: "optional",
    payments: "yes",
    scheduling: "yes",
    coupons: "yes",
    native: "wrappers",
    exports: "no real code export",
    hosting: "Bubble hosted",
    skill: "amateur-plus",
    line: "The no-code workhorse. Slow to love, hard to outgrow overnight.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "Adalo",
    name: "Adalo",
    url: "https://www.adalo.com/",
    category: "classic",
    can: ["customer app", "employee app", "scheduling", "service info", "mobile-first"],
    cannot: ["complex public marketing site", "heavy coupons engine"],
    strengths: ["mobile layouts", "amateur makers"],
    weaknesses: ["web SEO", "scale"],
    pricing: "subscription",
    auth: "optional",
    payments: "yes",
    scheduling: "yes",
    coupons: "unknown",
    native: "store wrappers",
    exports: "unknown",
    hosting: "Adalo hosted",
    skill: "amateur",
    line: "Mobile screens first. A site is an afterthought.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "FlutterFlow",
    name: "FlutterFlow",
    url: "https://www.flutterflow.io/",
    category: "classic",
    can: ["customer app", "employee app", "scheduling", "firebase", "code export"],
    cannot: ["no-login brochure site as the main product", "coupons-as-a-feature without stitch"],
    strengths: ["real Flutter export", "pretty mobile"],
    weaknesses: ["amateur ceiling if you never open the code"],
    pricing: "subscription",
    auth: "usually on",
    payments: "yes",
    scheduling: "yes",
    coupons: "stitch",
    native: "yes",
    exports: "Flutter code",
    hosting: "Firebase / self",
    skill: "amateur-plus",
    line: "Draw a mobile app. Keep the code if you grow up.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "Draftbit",
    name: "Draftbit",
    url: "https://draftbit.com/",
    category: "classic",
    can: ["customer app", "employee app", "react native export"],
    cannot: ["marketing website", "no-code coupons"],
    strengths: ["exportable RN"],
    weaknesses: ["not a site builder"],
    pricing: "subscription",
    auth: "yes",
    payments: "stitch",
    scheduling: "stitch",
    coupons: "stitch",
    native: "yes",
    exports: "React Native",
    hosting: "you host",
    skill: "amateur-plus",
    line: "A visual React Native stall.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "Thunkable",
    name: "Thunkable",
    url: "https://thunkable.com/",
    category: "classic",
    can: ["customer app", "employee app"],
    cannot: ["SEO website", "complex coupons"],
    strengths: ["classroom mobile"],
    weaknesses: ["production polish"],
    pricing: "freemium",
    auth: "optional",
    payments: "unknown",
    scheduling: "unknown",
    coupons: "unknown",
    native: "yes",
    exports: "limited",
    hosting: "Thunkable",
    skill: "amateur",
    line: "Blocks. Phones. School energy.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "GoodBarber",
    name: "GoodBarber",
    url: "https://www.goodbarber.com/",
    category: "classic",
    can: ["customer app", "content app", "shop"],
    cannot: ["custom employee protocol app"],
    strengths: ["templated mobile shops"],
    weaknesses: ["unique workflows"],
    pricing: "subscription",
    auth: "optional",
    payments: "yes",
    scheduling: "unknown",
    coupons: "yes",
    native: "yes",
    exports: "no",
    hosting: "GoodBarber",
    skill: "amateur",
    line: "A templated shop in your pocket.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "WeWeb",
    name: "WeWeb",
    url: "https://www.weweb.io/",
    category: "classic",
    can: ["website", "web app", "no-login public pages"],
    cannot: ["native store binary"],
    strengths: ["front-end on your own backend"],
    weaknesses: ["you still need Xano/etc for data"],
    pricing: "subscription",
    auth: "optional",
    payments: "stitch",
    scheduling: "stitch",
    coupons: "stitch",
    native: "no",
    exports: "vue-ish",
    hosting: "WeWeb or self",
    skill: "amateur-plus",
    line: "Visual front. Bring your own backend.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "AppSheet",
    name: "AppSheet",
    url: "https://about.appsheet.com/",
    category: "internal",
    can: ["employee app", "scheduling", "protocols", "sheets"],
    cannot: ["pretty marketing site", "consumer coupons shop"],
    strengths: ["Google-adjacent field apps"],
    weaknesses: ["looks like work software because it is"],
    pricing: "Google Workspace add-on",
    auth: "usually Google identity",
    payments: "no",
    scheduling: "yes",
    coupons: "no",
    native: "wrappers",
    exports: "no",
    hosting: "Google",
    skill: "amateur",
    line: "The van. The clipboard. A sheet behind it.",
    last_verified: "2026-09",
    provenance: "internal",
  }),
  f({
    id: "Zoho Creator",
    name: "Zoho Creator",
    url: "https://www.zoho.com/creator/",
    category: "internal",
    can: ["employee app", "scheduling", "customer portal"],
    cannot: ["playful consumer brand site"],
    strengths: ["Zoho suite glue"],
    weaknesses: ["looks like Zoho"],
    pricing: "subscription",
    auth: "yes",
    payments: "yes",
    scheduling: "yes",
    coupons: "unknown",
    native: "wrappers",
    exports: "unknown",
    hosting: "Zoho",
    skill: "amateur-plus",
    line: "Business apps that already live in Zoho.",
    last_verified: "2026-09",
    provenance: "internal",
  }),
  f({
    id: "Retool",
    name: "Retool",
    url: "https://retool.com/",
    category: "internal",
    can: ["employee app", "admin", "scheduling boards"],
    cannot: ["public marketing site", "consumer coupons", "no-login consumer app"],
    strengths: ["internal tools fast"],
    weaknesses: ["not for civilians"],
    pricing: "per seat",
    auth: "required",
    payments: "no",
    scheduling: "yes as UI",
    coupons: "no",
    native: "no",
    exports: "limited",
    hosting: "Retool / self",
    skill: "pro",
    line: "Internal dashboards. Not a storefront.",
    last_verified: "2026-09",
    provenance: "internal",
  }),
  f({
    id: "Appsmith",
    name: "Appsmith",
    url: "https://www.appsmith.com/",
    category: "internal",
    can: ["employee app", "admin"],
    cannot: ["consumer website", "coupons shop"],
    strengths: ["open-source internal"],
    weaknesses: ["public brand"],
    pricing: "open / cloud",
    auth: "required",
    payments: "no",
    scheduling: "as UI",
    coupons: "no",
    native: "no",
    exports: "unknown",
    hosting: "self or cloud",
    skill: "pro",
    line: "Retool’s open cousin.",
    last_verified: "2026-09",
    provenance: "internal",
  }),
  f({
    id: "Budibase",
    name: "Budibase",
    url: "https://budibase.com/",
    category: "internal",
    can: ["employee app", "forms", "approvals"],
    cannot: ["consumer marketing site"],
    strengths: ["open internal apps"],
    weaknesses: ["pretty public web"],
    pricing: "open / cloud",
    auth: "yes",
    payments: "no",
    scheduling: "unknown",
    coupons: "no",
    native: "no",
    exports: "unknown",
    hosting: "self or cloud",
    skill: "amateur-plus",
    line: "Internal apps you can self-host.",
    last_verified: "2026-09",
    provenance: "internal",
  }),
  f({
    id: "ToolJet",
    name: "ToolJet",
    url: "https://www.tooljet.com/",
    category: "internal",
    can: ["employee app", "admin"],
    cannot: ["consumer site"],
    strengths: ["open internal"],
    weaknesses: ["public brand"],
    pricing: "open / cloud",
    auth: "yes",
    payments: "no",
    scheduling: "unknown",
    coupons: "no",
    native: "no",
    exports: "unknown",
    hosting: "self or cloud",
    skill: "pro",
    line: "Another internal stall. Fine for the shop. Not the storefront.",
    last_verified: "2026-09",
    provenance: "internal",
  }),
  f({
    id: "Superblocks",
    name: "Superblocks",
    url: "https://www.superblocks.com/",
    category: "internal",
    can: ["employee app", "admin"],
    cannot: ["consumer coupons site"],
    strengths: ["enterprise internal"],
    weaknesses: ["amateur consumer"],
    pricing: "enterprise",
    auth: "required",
    payments: "no",
    scheduling: "as UI",
    coupons: "no",
    native: "no",
    exports: "unknown",
    hosting: "cloud",
    skill: "pro",
    line: "Internal, with a sales call.",
    last_verified: "2026-09",
    provenance: "internal",
  }),
  f({
    id: "Noloco",
    name: "Noloco",
    url: "https://noloco.io/",
    category: "internal",
    can: ["client portal", "employee app", "airtable"],
    cannot: ["game", "marketing-only one-pager as the point"],
    strengths: ["portals on data"],
    weaknesses: ["brand theater"],
    pricing: "subscription",
    auth: "yes for portals",
    payments: "unknown",
    scheduling: "yes",
    coupons: "unknown",
    native: "no",
    exports: "unknown",
    hosting: "Noloco",
    skill: "amateur-plus",
    line: "A portal on someone else’s tables.",
    last_verified: "2026-09",
    provenance: "internal",
  }),
  f({
    id: "Mendix",
    name: "Mendix",
    url: "https://www.mendix.com/",
    category: "lcap",
    can: ["employee app", "enterprise workflow"],
    cannot: ["amateur weekend build", "no-login consumer coupons site as the brief"],
    strengths: ["enterprise LCAP"],
    weaknesses: ["price", "sales cycle", "amateur"],
    pricing: "enterprise",
    auth: "required",
    payments: "enterprise",
    scheduling: "yes",
    coupons: "unknown",
    native: "yes",
    exports: "unknown",
    hosting: "Mendix / private",
    skill: "pro",
    line: "A factory that wants a contract.",
    last_verified: "2026-09",
    provenance: "lcap",
  }),
  f({
    id: "OutSystems",
    name: "OutSystems",
    url: "https://www.outsystems.com/",
    category: "lcap",
    can: ["employee app", "enterprise"],
    cannot: ["amateur coupons website"],
    strengths: ["enterprise"],
    weaknesses: ["amateur", "cost"],
    pricing: "enterprise",
    auth: "required",
    payments: "enterprise",
    scheduling: "yes",
    coupons: "unknown",
    native: "yes",
    exports: "unknown",
    hosting: "OutSystems",
    skill: "pro",
    line: "Same aisle as Mendix. Bring procurement.",
    last_verified: "2026-09",
    provenance: "lcap",
  }),
  f({
    id: "Power Apps",
    name: "Power Apps",
    url: "https://www.microsoft.com/power-platform/products/power-apps",
    category: "lcap",
    can: ["employee app", "scheduling", "protocols", "Microsoft 365"],
    cannot: ["public coupons marketing site", "no-login consumer brand"],
    strengths: ["if you already live in Microsoft"],
    weaknesses: ["looks like Office", "licensing maze"],
    pricing: "Microsoft 365 add-on",
    auth: "Microsoft identity required",
    payments: "no",
    scheduling: "yes",
    coupons: "no",
    native: "wrappers",
    exports: "no",
    hosting: "Azure",
    skill: "pro",
    line: "The employee app if IT already chose Microsoft.",
    last_verified: "2026-09",
    provenance: "lcap",
  }),
  f({
    id: "Salesforce Lightning",
    name: "Salesforce Lightning",
    url: "https://www.salesforce.com/",
    category: "lcap",
    can: ["CRM", "employee app"],
    cannot: ["amateur website", "no-login coupons page as the product"],
    strengths: ["CRM gravity"],
    weaknesses: ["everything is Salesforce"],
    pricing: "enterprise",
    auth: "required",
    payments: "yes",
    scheduling: "yes",
    coupons: "unknown",
    native: "wrappers",
    exports: "no",
    hosting: "Salesforce",
    skill: "pro",
    line: "You don’t pick this for a pest-control homepage.",
    last_verified: "2026-09",
    provenance: "lcap",
  }),
  f({
    id: "Appian",
    name: "Appian",
    url: "https://appian.com/",
    category: "lcap",
    can: ["enterprise workflow"],
    cannot: ["amateur consumer site"],
    strengths: ["process"],
    weaknesses: ["amateur"],
    pricing: "enterprise",
    auth: "required",
    payments: "unknown",
    scheduling: "yes",
    coupons: "no",
    native: "unknown",
    exports: "unknown",
    hosting: "Appian",
    skill: "pro",
    line: "Workflow for people with a PMO.",
    last_verified: "2026-09",
    provenance: "lcap",
  }),
  f({
    id: "ServiceNow App Engine",
    name: "ServiceNow App Engine",
    url: "https://www.servicenow.com/",
    category: "lcap",
    can: ["IT employee app"],
    cannot: ["consumer coupons website"],
    strengths: ["ITSM"],
    weaknesses: ["amateur consumer"],
    pricing: "enterprise",
    auth: "required",
    payments: "no",
    scheduling: "yes",
    coupons: "no",
    native: "unknown",
    exports: "unknown",
    hosting: "ServiceNow",
    skill: "pro",
    line: "Tickets. Not a storefront.",
    last_verified: "2026-09",
    provenance: "lcap",
  }),
  f({
    id: "Oracle APEX",
    name: "Oracle APEX",
    url: "https://apex.oracle.com/",
    category: "lcap",
    can: ["database app", "employee app"],
    cannot: ["amateur no-code coupons site"],
    strengths: ["Oracle shops"],
    weaknesses: ["amateur", "Oracle"],
    pricing: "included with Oracle DB",
    auth: "yes",
    payments: "unknown",
    scheduling: "yes",
    coupons: "unknown",
    native: "no",
    exports: "unknown",
    hosting: "Oracle",
    skill: "pro",
    line: "If you already have Oracle, maybe. If you don’t, no.",
    last_verified: "2026-09",
    provenance: "lcap",
  }),
  f({
    id: "Lovable",
    name: "Lovable",
    url: "https://lovable.dev/",
    category: "vibe",
    can: ["website", "saas ui", "crud", "supabase auth"],
    cannot: ["guaranteed no-login coupons+scheduling+employee app as one click", "native store binary"],
    strengths: ["pretty front-ends", "amateur vibe"],
    weaknesses: ["deep custom backend", "offline", "multi-app employee protocols"],
    pricing: "subscription credits",
    auth: "optional via stitch",
    payments: "stitch",
    scheduling: "stitch",
    coupons: "stitch",
    native: "no",
    exports: "code",
    hosting: "Lovable / you",
    skill: "amateur",
    line: "Pretty front-ends, fast. The look is the pitch.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "Bolt",
    name: "Bolt.new",
    url: "https://bolt.new/",
    category: "vibe",
    can: ["website", "prototype", "demo"],
    cannot: ["long-lived employee protocol app without stitch", "native"],
    strengths: ["instant front-end"],
    weaknesses: ["durable backend", "scheduling as a product"],
    pricing: "credits",
    auth: "stitch",
    payments: "stitch",
    scheduling: "stitch",
    coupons: "stitch",
    native: "no",
    exports: "code",
    hosting: "StackBlitz-ish",
    skill: "amateur",
    line: "Front-end first. Deploy quick. The rest is a stitch.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "v0",
    name: "v0",
    url: "https://v0.dev/",
    category: "vibe",
    can: ["ui", "marketing page"],
    cannot: ["hosting as the product", "scheduling backend", "employee app"],
    strengths: ["shadcn UI from a sentence"],
    weaknesses: ["you own auth, data, deploy"],
    pricing: "credits",
    auth: "no",
    payments: "no",
    scheduling: "no",
    coupons: "no",
    native: "no",
    exports: "react",
    hosting: "you",
    skill: "amateur-plus",
    line: "UI. You still need a factory that ships.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "Replit",
    name: "Replit Agent",
    url: "https://replit.com/",
    category: "vibe",
    can: ["website", "prototype", "hosted app"],
    cannot: ["native store"],
    strengths: ["hosting is the product"],
    weaknesses: ["polish", "multi-app field ops"],
    pricing: "subscription",
    auth: "stitch",
    payments: "stitch",
    scheduling: "stitch",
    coupons: "stitch",
    native: "no",
    exports: "code",
    hosting: "Replit",
    skill: "amateur",
    line: "A computer in the tab.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "Base44",
    name: "Base44",
    url: "https://base44.com/",
    category: "vibe",
    can: ["website", "mvp", "crud"],
    cannot: ["native", "guaranteed field-ops suite"],
    strengths: ["chat-to-app"],
    weaknesses: ["Wix-adjacent gravity after ~Jun 2025 acquisition — still its own product"],
    pricing: "unknown",
    auth: "unknown",
    payments: "unknown",
    scheduling: "unknown",
    coupons: "unknown",
    native: "no",
    exports: "unknown",
    hosting: "Base44",
    skill: "amateur",
    line: "Chat-to-app stall. Treat it like Bolt’s cousin. Wix bought it; it still ships as Base44.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "Rork",
    name: "Rork",
    url: "https://rork.ai/",
    category: "vibe",
    can: ["mobile", "customer app"],
    cannot: ["SEO website as the main thing"],
    strengths: ["mobile-leaning vibe"],
    weaknesses: ["web-first businesses"],
    pricing: "unknown",
    auth: "unknown",
    payments: "unknown",
    scheduling: "unknown",
    coupons: "unknown",
    native: "aiming yes",
    exports: "unknown",
    hosting: "unknown",
    skill: "amateur",
    line: "Mobile-leaning vibe builder.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "CatDoes",
    name: "CatDoes",
    url: "https://catdoes.com/",
    category: "vibe",
    can: ["mobile app"],
    cannot: ["unknown"],
    strengths: ["unknown"],
    weaknesses: ["unknown"],
    pricing: "unknown",
    auth: "unknown",
    payments: "unknown",
    scheduling: "unknown",
    coupons: "unknown",
    native: "unknown",
    exports: "unknown",
    hosting: "unknown",
    skill: "amateur",
    line: "Mobile vibe stall. Fields stay unknown until verified.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "Emergent",
    name: "Emergent",
    url: "https://app.emergent.sh/",
    category: "vibe",
    can: ["website", "business mvp", "hosted app"],
    cannot: ["offline PWA guarantee", "native store binary"],
    strengths: ["agents ship something"],
    weaknesses: ["game feel", "field-ops nuance"],
    pricing: "subscription / contests",
    auth: "unknown",
    payments: "unknown",
    scheduling: "unknown",
    coupons: "unknown",
    native: "no",
    exports: "unknown",
    hosting: "Emergent",
    skill: "amateur",
    line: "Agents design, code, and deploy. Contests on the side.",
    last_verified: "2026-09",
    provenance: "amateur",
    sponsored: true,
  }),
  f({
    id: "Softgen",
    name: "Softgen",
    url: "https://softgen.ai/",
    category: "vibe",
    can: ["website", "mvp"],
    cannot: ["unknown"],
    strengths: ["unknown"],
    weaknesses: ["unknown"],
    pricing: "unknown",
    auth: "unknown",
    payments: "unknown",
    scheduling: "unknown",
    coupons: "unknown",
    native: "unknown",
    exports: "unknown",
    hosting: "unknown",
    skill: "amateur",
    line: "Another chat-to-app stall. Unknown until poked.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "Anything",
    name: "Anything",
    url: "https://www.anything.com/",
    category: "vibe",
    can: ["website", "mvp"],
    cannot: ["unknown"],
    strengths: ["ex-Create.xyz"],
    weaknesses: ["unknown"],
    pricing: "unknown",
    auth: "unknown",
    payments: "unknown",
    scheduling: "unknown",
    coupons: "unknown",
    native: "unknown",
    exports: "unknown",
    hosting: "unknown",
    skill: "amateur",
    line: "Anything (ex-Create.xyz). Name is the dare.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "A0",
    name: "a0.dev",
    url: "https://a0.dev/",
    category: "vibe",
    can: ["mobile"],
    cannot: ["unknown"],
    strengths: ["unknown"],
    weaknesses: ["unknown"],
    pricing: "unknown",
    auth: "unknown",
    payments: "unknown",
    scheduling: "unknown",
    coupons: "unknown",
    native: "unknown",
    exports: "unknown",
    hosting: "unknown",
    skill: "amateur",
    line: "a0.dev. Mobile-ish. Fields unknown.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "Grok",
    name: "Grok Build",
    url: "https://grok.com/",
    category: "vibe",
    can: ["website", "pwa", "prototype", "directory", "tool"],
    cannot: ["native iOS binary", "app store listing", "enterprise SSO as a product"],
    strengths: ["iterate in the thread", "running PWA"],
    weaknesses: ["you stay in the thread to wire APIs"],
    pricing: "subscription",
    auth: "stitch",
    payments: "stitch",
    scheduling: "stitch",
    coupons: "stitch",
    native: "PWA",
    exports: "code in the workspace",
    hosting: "grok.me / you",
    skill: "amateur",
    line: "Chat, get a running PWA, iterate in the same thread.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "Floot",
    name: "Floot",
    url: "https://floot.com/",
    category: "vibe",
    can: ["saas", "crud", "auth"],
    cannot: ["game", "pixel-perfect brand"],
    strengths: ["full-stack vibe"],
    weaknesses: ["unknown coupons/scheduling as first-class"],
    pricing: "unknown",
    auth: "yes",
    payments: "unknown",
    scheduling: "unknown",
    coupons: "unknown",
    native: "no",
    exports: "unknown",
    hosting: "Floot",
    skill: "amateur",
    line: "Full-stack vibe coding with opinions about shipping.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "Plasmic",
    name: "Plasmic",
    url: "https://www.plasmic.app/",
    category: "visual",
    can: ["website", "cms pages"],
    cannot: ["employee protocol app as the point"],
    strengths: ["visual on a real codebase"],
    weaknesses: ["you still code"],
    pricing: "subscription",
    auth: "stitch",
    payments: "stitch",
    scheduling: "stitch",
    coupons: "stitch",
    native: "no",
    exports: "into your repo",
    hosting: "you",
    skill: "pro",
    line: "Visual pages on a real repo.",
    last_verified: "2026-09",
    provenance: "pro",
  }),
  f({
    id: "Builder.io",
    name: "Builder.io",
    url: "https://www.builder.io/",
    category: "visual",
    can: ["website", "cms"],
    cannot: ["field employee app"],
    strengths: ["marketing sites on your stack"],
    weaknesses: ["ops apps"],
    pricing: "subscription",
    auth: "stitch",
    payments: "stitch",
    scheduling: "no",
    coupons: "cms",
    native: "no",
    exports: "into your stack",
    hosting: "you",
    skill: "pro",
    line: "CMS for people who already have a site.",
    last_verified: "2026-09",
    provenance: "pro",
  }),
  f({
    id: "Toddle",
    name: "Toddle",
    url: "https://toddle.dev/",
    category: "visual",
    can: ["web app"],
    cannot: ["unknown after Nordcraft pivot — watch"],
    strengths: ["visual web apps"],
    weaknesses: ["watch the Nordcraft pivot"],
    pricing: "unknown",
    auth: "unknown",
    payments: "unknown",
    scheduling: "unknown",
    coupons: "unknown",
    native: "no",
    exports: "unknown",
    hosting: "unknown",
    skill: "amateur-plus",
    line: "Visual web apps. Watch the Nordcraft pivot.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "Xano",
    name: "Xano",
    url: "https://www.xano.com/",
    category: "backend",
    can: ["backend", "auth", "api"],
    cannot: ["frontend website alone", "no-login site as the whole product"],
    strengths: ["no-code backend"],
    weaknesses: ["not a UI factory"],
    pricing: "subscription",
    auth: "yes",
    payments: "stitch",
    scheduling: "as data",
    coupons: "as data",
    native: "no",
    exports: "API",
    hosting: "Xano",
    skill: "amateur-plus",
    line: "The backend if WeWeb is the face.",
    last_verified: "2026-09",
    provenance: "stitch",
  }),
  f({
    id: "Wized",
    name: "Wized",
    url: "https://www.wized.com/",
    category: "backend",
    can: ["webflow logic", "auth"],
    cannot: ["employee native app"],
    strengths: ["Webflow that acts like an app"],
    weaknesses: ["you still need Webflow"],
    pricing: "subscription",
    auth: "yes",
    payments: "yes",
    scheduling: "stitch",
    coupons: "stitch",
    native: "no",
    exports: "no",
    hosting: "with Webflow",
    skill: "amateur-plus",
    line: "Logic for a Webflow site.",
    last_verified: "2026-09",
    provenance: "stitch",
  }),
  f({
    id: "Directual",
    name: "Directual",
    url: "https://www.directual.com/",
    category: "backend",
    can: ["backend", "web app"],
    cannot: ["unknown native"],
    strengths: ["no-code backend + UI"],
    weaknesses: ["unknown amateur polish"],
    pricing: "subscription",
    auth: "yes",
    payments: "unknown",
    scheduling: "yes",
    coupons: "unknown",
    native: "unknown",
    exports: "unknown",
    hosting: "Directual",
    skill: "amateur-plus",
    line: "No-code backend with a face.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "Backendless",
    name: "Backendless",
    url: "https://backendless.com/",
    category: "backend",
    can: ["backend", "realtime"],
    cannot: ["pretty site alone"],
    strengths: ["mBaaS"],
    weaknesses: ["you still design the client"],
    pricing: "subscription",
    auth: "yes",
    payments: "unknown",
    scheduling: "as data",
    coupons: "as data",
    native: "client SDKs",
    exports: "API",
    hosting: "Backendless",
    skill: "pro",
    line: "A backend with an SDK, not a storefront.",
    last_verified: "2026-09",
    provenance: "stitch",
  }),
  f({
    id: "Bravo Studio",
    name: "Bravo Studio",
    url: "https://www.bravostudio.app/",
    category: "classic",
    can: ["customer app", "figma to mobile"],
    cannot: ["website SEO"],
    strengths: ["designers ship mobile"],
    weaknesses: ["web"],
    pricing: "subscription",
    auth: "optional",
    payments: "unknown",
    scheduling: "unknown",
    coupons: "unknown",
    native: "yes",
    exports: "limited",
    hosting: "Bravo",
    skill: "amateur",
    line: "Figma in, mobile out.",
    last_verified: "2026-09",
    provenance: "amateur",
  }),
  f({
    id: "BuildFire",
    name: "BuildFire",
    url: "https://buildfire.com/",
    category: "classic",
    can: ["customer app", "content app"],
    cannot: ["tiny amateur coupons site cheaply"],
    strengths: ["done-for-you mobile"],
    weaknesses: ["price for a solo exterminator"],
    pricing: "high subscription",
    auth: "optional",
    payments: "yes",
    scheduling: "yes",
    coupons: "yes",
    native: "yes",
    exports: "no",
    hosting: "BuildFire",
    skill: "amateur",
    line: "A mobile vendor. Bring a budget.",
    last_verified: "2026-09",
    provenance: "pro",
  }),
  f({
    id: "Betty Blocks",
    name: "Betty Blocks",
    url: "https://www.bettyblocks.com/",
    category: "lcap",
    can: ["enterprise app"],
    cannot: ["amateur coupons website"],
    strengths: ["enterprise no-code"],
    weaknesses: ["amateur"],
    pricing: "enterprise",
    auth: "yes",
    payments: "unknown",
    scheduling: "yes",
    coupons: "unknown",
    native: "unknown",
    exports: "unknown",
    hosting: "Betty Blocks",
    skill: "pro",
    line: "Enterprise no-code. Not the pest-control homepage.",
    last_verified: "2026-09",
    provenance: "lcap",
  }),
  f({
    id: "Kissflow",
    name: "Kissflow",
    url: "https://kissflow.com/",
    category: "internal",
    can: ["workflow", "employee app"],
    cannot: ["consumer site"],
    strengths: ["process"],
    weaknesses: ["storefront"],
    pricing: "subscription",
    auth: "yes",
    payments: "no",
    scheduling: "yes",
    coupons: "no",
    native: "no",
    exports: "unknown",
    hosting: "Kissflow",
    skill: "pro",
    line: "Workflow. Not a shop window.",
    last_verified: "2026-09",
    provenance: "internal",
  }),
];

export const STITCH_WATCH = [
  { id: "Cursor", line: "An editor with a brain. Not a one-click factory." },
  { id: "Claude", line: "Long-context pair programmer. No deploy button." },
  { id: "Vanilla", line: "You and a text file. If the app is a page, skip the builders." },
];

type Need = {
  id: string;
  words: RegExp;
  blocks: (f: Factory) => string | null;
};

const NEEDS: Need[] = [
  {
    id: "coupons",
    words: /coupon/,
    blocks: (x) => (x.coupons === "no" || x.cannot.some((c) => /coupon/.test(c)) ? "cannot do coupons" : null),
  },
  {
    id: "scheduling",
    words: /schedul|appointment|booking|calendar/,
    blocks: (x) =>
      x.scheduling === "no" || x.cannot.some((c) => /schedul/.test(c)) ? "cannot do scheduling" : null,
  },
  {
    id: "website",
    words: /website|homepage|marketing site|service info/,
    blocks: (x) =>
      x.cannot.some((c) => /website|marketing site|storefront|public/.test(c)) || x.can.includes("employee app") && !x.can.includes("website") && !x.can.includes("customer app")
        ? "cannot do a public website"
        : null,
  },
  {
    id: "no-login",
    words: /no (identity )?login|without (a )?login|no identity|public page/,
    blocks: (x) =>
      x.auth === "required" ||
      x.auth.includes("required") ||
      x.cannot.some((c) => /no-login|public without auth|consumer/.test(c))
        ? "requires identity / cannot ship a public no-login surface"
        : null,
  },
  {
    id: "customer-app",
    words: /customer (app|scheduling)|client app/,
    blocks: (x) =>
      !x.can.includes("customer app") && !x.can.includes("website") && !x.can.includes("client portal")
        ? "no customer-facing app"
        : null,
  },
  {
    id: "employee-app",
    words: /employee app|staff app|protocols|field/,
    blocks: (x) => (!x.can.includes("employee app") ? "no employee / protocol app" : null),
  },
  {
    id: "amateur",
    words: /amateur|no.?code|i(?:'| a)m not a (dev|coder)|solo/,
    blocks: (x) =>
      x.provenance === "lcap" || x.skill === "pro" && x.pricing.includes("enterprise")
        ? "enterprise / LCAP — wrong shop for an amateur"
        : null,
  },
  {
    id: "native",
    words: /native ios|app store|play store binary/,
    blocks: (x) => (x.native === "no" ? "no native store binary" : null),
  },
  {
    id: "payments",
    words: /payment|checkout|stripe/,
    blocks: (x) => (x.payments === "no" ? "no payments" : null),
  },
];

export function matchFactories(prompt: string, lens: "vibe" | "all" = "vibe") {
  const q = prompt.toLowerCase();
  const active = NEEDS.filter((n) => n.words.test(q));
  const scored: { factory: Factory; score: number; reasons: string[] }[] = [];
  const cut: { factory: Factory; reasons: string[] }[] = [];

  for (const factory of FACTORIES) {
    if (factory.watch) continue;
    if (lens === "vibe" && (factory.provenance === "lcap" || factory.provenance === "pro" && factory.category === "lcap")) {
      cut.push({ factory, reasons: ["VIBE lens — pro/LCAP parked"] });
      continue;
    }
    const reasons = active.map((n) => n.blocks(factory)).filter((r): r is string => Boolean(r));
    if (reasons.length) {
      cut.push({ factory, reasons });
      continue;
    }
    let score = 0;
    for (const c of factory.can) if (q.includes(c.split(" ")[0])) score += 2;
    if (factory.skill.includes("amateur") && /amateur/.test(q)) score += 4;
    if (factory.provenance === "amateur") score += 1;
    if (factory.scheduling === "yes" && /schedul/.test(q)) score += 3;
    if ((factory.coupons === "yes" || factory.coupons === "yes via data") && /coupon/.test(q)) score += 3;
    if (factory.auth === "optional" && /no (identity )?login/.test(q)) score += 3;
    if (factory.can.includes("employee app") && /employee/.test(q)) score += 3;
    if (factory.can.includes("website") && /website/.test(q)) score += 2;
    if (factory.cannot.includes("unknown") && factory.can.includes("unknown")) score -= 1;
    scored.push({ factory, score, reasons: [] });
  }

  scored.sort((a, b) => b.score - a.score);
  const top: Factory[] = scored.slice(0, 3).map((s) => s.factory);
  if (top.length < 3) {
    const filler = cut
      .filter((c) => c.factory.provenance === "amateur" && !top.some((t) => t.id === c.factory.id))
      .sort((a, b) => a.reasons.length - b.reasons.length);
    for (const c of filler) {
      if (top.length >= 3) break;
      top.push(c.factory);
    }
  }
  const sponsored =
    FACTORIES.find((x) => x.sponsored && !top.some((t) => t.id === x.id)) || FACTORIES.find((x) => x.sponsored);
  const stitch =
    /api|stitch|code|repo/.test(q) || active.length >= 3
      ? STITCH_WATCH[0]
      : undefined;
  return { top, sponsored, cut: cut.slice(0, 8), stitch, active: active.map((a) => a.id) };
}
