#!/usr/bin/env python3
"""Emit src/lib/catalog-more.ts — real browser apps / PWAs."""
from pathlib import Path

# id, name, url, developer, genres csv, tagline
ROWS: list[tuple[str, str, str, str, str, str]] = []


def add(i, name, url, dev, genres, tag="In a tab. No store clerk."):
    ROWS.append((i, name, url, dev, genres, tag))


# --- News ---
news = [
    ("theguardian", "The Guardian", "https://www.theguardian.com/", "Guardian", "The paper that never clocks out."),
    ("washingtonpost", "The Washington Post", "https://www.washingtonpost.com/", "The Washington Post", "Democracy dies in darkness. The tab does not."),
    ("wsj", "WSJ", "https://www.wsj.com/", "Dow Jones", "Markets, with a paywall personality."),
    ("ft", "Financial Times", "https://www.ft.com/", "Financial Times", "Pink paper, browser ink."),
    ("economist", "The Economist", "https://www.economist.com/", "The Economist", "Briefings for people who brief."),
    ("reuters", "Reuters", "https://www.reuters.com/", "Reuters", "Wire first."),
    ("apnews", "AP News", "https://apnews.com/", "Associated Press", "The wire, still."),
    ("bloomberg", "Bloomberg", "https://www.bloomberg.com/", "Bloomberg", "Terminal energy in a tab."),
    ("aljazeera", "Al Jazeera", "https://www.aljazeera.com/", "Al Jazeera", "World desk, no costume."),
    ("dw", "DW", "https://www.dw.com/", "Deutsche Welle", "Germany explains the room."),
    ("france24", "France 24", "https://www.france24.com/", "France 24", "Paris, broadcasting."),
    ("nhk", "NHK World", "https://www3.nhk.or.jp/nhkworld/", "NHK", "Tokyo, in English."),
    ("abc-au", "ABC Australia", "https://www.abc.net.au/", "ABC", "Aunty, down under."),
    ("cbc", "CBC", "https://www.cbc.ca/", "CBC", "Canada, still public."),
    ("theage", "The Age", "https://www.theage.com.au/", "Nine", "Melbourne’s paper."),
    ("smh", "Sydney Morning Herald", "https://www.smh.com.au/", "Nine", "Harbor news."),
    ("scmp", "SCMP", "https://www.scmp.com/", "SCMP", "Hong Kong, watching."),
    ("straitstimes", "The Straits Times", "https://www.straitstimes.com/", "SPH", "Singapore, concise."),
    ("hindu", "The Hindu", "https://www.thehindu.com/", "The Hindu", "Chennai, thorough."),
    ("timesofindia", "Times of India", "https://timesofindia.indiatimes.com/", "TOI", "India, loudly."),
    ("ndtv", "NDTV", "https://www.ndtv.com/", "NDTV", "Delhi, live."),
    ("haaretz", "Haaretz", "https://www.haaretz.com/", "Haaretz", "Tel Aviv, arguing."),
    ("jpost", "Jerusalem Post", "https://www.jpost.com/", "Jerusalem Post", "The other desk."),
    ("elpais", "El País", "https://elpais.com/", "PRISA", "Madrid, writing."),
    ("lemonde", "Le Monde", "https://www.lemonde.fr/", "Le Monde", "Paris, still serious."),
    ("spiegel", "Der Spiegel", "https://www.spiegel.de/", "Spiegel", "Hamburg investigates."),
    ("zeit", "Die Zeit", "https://www.zeit.de/", "Die Zeit", "Long, German, worth it."),
    ("corriere", "Corriere", "https://www.corriere.it/", "RCS", "Milan’s morning."),
    ("repubblica", "la Repubblica", "https://www.repubblica.it/", "GEDI", "Rome, scrolling."),
    ("folha", "Folha", "https://www.folha.uol.com.br/", "Folha", "São Paulo."),
    ("globo", "G1", "https://g1.globo.com/", "Globo", "Brazil, live."),
    ("clarin", "Clarín", "https://www.clarin.com/", "Clarín", "Buenos Aires."),
    ("lanacion", "La Nación", "https://www.lanacion.com.ar/", "La Nación", "Argentina’s other paper."),
    ("eluniversal", "El Universal", "https://www.eluniversal.com.mx/", "El Universal", "Mexico City."),
    ("theglobe", "The Globe and Mail", "https://www.theglobeandmail.com/", "Globe and Mail", "Canada’s paper of record, allegedly."),
    ("politico", "Politico", "https://www.politico.com/", "Politico", "Playbook people."),
    ("thehill", "The Hill", "https://thehill.com/", "Nexstar", "Congress, as sport."),
    ("axios", "Axios", "https://www.axios.com/", "Axios", "Smart brevity. That’s the bit."),
    ("semafor", "Semafor", "https://www.semafor.com/", "Semafor", "A newer desk."),
    ("theatlantic", "The Atlantic", "https://www.theatlantic.com/", "The Atlantic", "Essays that take the afternoon."),
    ("newyorker", "The New Yorker", "https://www.newyorker.com/", "Condé Nast", "Cartoons and long knives."),
    ("wired", "WIRED", "https://www.wired.com/", "Condé Nast", "The gadget with a thesis."),
    ("techcrunch", "TechCrunch", "https://techcrunch.com/", "Yahoo", "Startups, announced."),
    ("theverge", "The Verge", "https://www.theverge.com/", "Vox", "Gadgets with feelings."),
    ("arstechnica", "Ars Technica", "https://arstechnica.com/", "Condé Nast", "Nerd paper of record."),
    ("engadget", "Engadget", "https://www.engadget.com/", "Yahoo", "The other gadget desk."),
    ("mashable", "Mashable", "https://mashable.com/", "Ziff Davis", "Internet, recapped."),
    ("vice", "VICE", "https://www.vice.com/", "VICE", "Still trying."),
    ("vox", "Vox", "https://www.vox.com/", "Vox", "Explainer energy."),
    ("slate", "Slate", "https://slate.com/", "Slate", "Takes, professionally."),
    ("salon", "Salon", "https://www.salon.com/", "Salon", "The other takes."),
    ("nypost", "New York Post", "https://nypost.com/", "News Corp", "Headlines that yell."),
    ("latimes", "Los Angeles Times", "https://www.latimes.com/", "LAT", "West coast paper."),
    ("chicagotribune", "Chicago Tribune", "https://www.chicagotribune.com/", "Tribune", "The hog butcher’s paper."),
    ("bostonglobe", "Boston Globe", "https://www.bostonglobe.com/", "Boston Globe", "Beantown, reported."),
    ("seattletimes", "Seattle Times", "https://www.seattletimes.com/", "Seattle Times", "Rain, with bylines."),
    ("denverpost", "The Denver Post", "https://www.denverpost.com/", "Digital First", "Mile high news."),
    ("miamiherald", "Miami Herald", "https://www.miamiherald.com/", "McClatchy", "The humidity desk."),
    ("houstonchronicle", "Houston Chronicle", "https://www.houstonchronicle.com/", "Hearst", "Energy capital, reported."),
    ("sfchronicle", "SF Chronicle", "https://www.sfchronicle.com/", "Hearst", "Fog and scoops."),
    ("propublica", "ProPublica", "https://www.propublica.org/", "ProPublica", "Nonprofit knives."),
    ("theintercept", "The Intercept", "https://theintercept.com/", "First Look", "Documents, please."),
    ("bellingcat", "Bellingcat", "https://www.bellingcat.com/", "Bellingcat", "OSINT as a sport."),
    ("404media", "404 Media", "https://www.404media.co/", "404 Media", "The internet, investigated."),
    ("platformer", "Platformer", "https://www.platformer.news/", "Platformer", "Casey, still typing."),
    ("stratechery", "Stratechery", "https://stratechery.com/", "Stratechery", "Aggregation theory, weekly."),
    ("kottke", "kottke.org", "https://kottke.org/", "Jason Kottke", "The blog that never died."),
    ("memex", "The Memex", "https://memex.marginalia.nu/", "Marginalia", "A search engine with opinions."),
    ("marginalia", "Marginalia Search", "https://search.marginalia.nu/", "Marginalia", "The independent index."),
    ("wapo-games", "WaPo Games", "https://www.washingtonpost.com/crossword/", "The Washington Post", "Crosswords in a tab."),
    ("nyt-games", "NYT Games", "https://www.nytimes.com/games", "The New York Times", "Wordle’s landlord."),
    ("sverigesradio", "Sveriges Radio", "https://sverigesradio.se/", "SR", "Sweden, speaking."),
    ("yle", "Yle", "https://yle.fi/", "Yle", "Finland, public."),
    ("nrk", "NRK", "https://www.nrk.no/", "NRK", "Norway, public."),
    ("dr-dk", "DR", "https://www.dr.dk/", "DR", "Denmark, public."),
    ("rte", "RTÉ", "https://www.rte.ie/", "RTÉ", "Ireland, on air."),
    ("nos", "NOS", "https://nos.nl/", "NOS", "The Netherlands, briefed."),
    ("vrt", "VRT", "https://www.vrt.be/", "VRT", "Flanders, public."),
    ("srf", "SRF", "https://www.srf.ch/", "SRG", "Switzerland, four languages."),
    ("orf", "ORF", "https://orf.at/", "ORF", "Austria, public."),
    ("tvn24", "TVN24", "https://tvn24.pl/", "TVN", "Poland, live."),
    ("pravda", "Ukrainska Pravda", "https://www.pravda.com.ua/", "UP", "Kyiv, reporting."),
    ("kyivindependent", "The Kyiv Independent", "https://kyivindependent.com/", "Kyiv Independent", "Ukraine, in English."),
    ("meduza", "Meduza", "https://meduza.io/", "Meduza", "Riga, watching Moscow."),
    ("novaya", "Novaya Gazeta Europe", "https://novayagazeta.eu/", "Novaya", "The paper that left."),
]
for i, n, u, d, t in news:
    add(i, n, u, d, "news", t)

# --- Games ---
games = [
    ("slither", "slither.io", "https://slither.io/", "Dave", "The worm. Always the worm."),
    ("agar", "Agar.io", "https://agar.io/", "Miniclip", "Eat. Get eaten."),
    ("diep", "diep.io", "https://diep.io/", "Diep", "Tanks. Circles. Regret."),
    ("shellshockers", "Shell Shockers", "https://shellshock.io/", "Blue Wizard", "Eggs with guns."),
    ("surviv", "surviv.io", "https://surviv.io/", "Surviv", "Battle royale in a tab."),
    ("evio", "ev.io", "https://ev.io/", "Evio", "FPS, no download."),
    ("littlealchemy", "Little Alchemy 2", "https://littlealchemy2.com/", "Recloak", "Combine. Wonder."),
    ("cookieclicker", "Cookie Clicker", "https://orteil.dashnet.org/cookieclicker/", "Orteil", "The original sin of idle."),
    ("candybox", "Candy Box 2", "https://candybox2.net/", "aniwey", "An ASCII that grew up."),
    ("universalpaperclips", "Universal Paperclips", "https://www.decisionproblem.com/paperclips/", "Frank Lantz", "The AI that wanted stationery."),
    ("nested", "Nested", "https://weavesilk.com/", "Silk", "Draw a silk universe."),
    ("weavesilk", "Silk", "https://weavesilk.com/", "Silk", "Symmetry as a toy."),
    ("quickdraw", "Quick, Draw!", "https://quickdraw.withgoogle.com/", "Google", "Doodle vs neural net."),
    ("semantris", "Semantris", "https://research.google.com/semantris/", "Google", "Word association as sport."),
    ("musiclab", "Chrome Music Lab", "https://musiclab.chromeexperiments.com/", "Google", "Sound, for kids and the rest."),
    ("autodraw", "AutoDraw", "https://www.autodraw.com/", "Google", "You sketch. It guesses."),
    ("sandspiel", "Sandspiel", "https://sandspiel.club/", "Max Bittker", "Falling sand, falling hours."),
    ("orbits", "Orbits", "https://orbits.zkga.me/", "DF", "Idle with gravity."),
    ("cityroads", "Anvaka city roads", "https://anvaka.github.io/city-roads/", "Anvaka", "Every road, one drawing."),
    ("window-swap", "WindowSwap", "https://www.window-swap.com/", "WindowSwap", "Someone else’s view."),
    ("radiooooo", "RADIOOOOO", "https://radiooooo.com/", "RADIOOOOO", "A decade, a country, a song."),
    ("poolsuite", "Poolsuite FM", "https://poolsuite.net/", "Poolsuite", "Summer that never ends."),
    ("nightcafe", "NightCafe", "https://nightcafe.studio/", "NightCafe", "Images from sentences."),
    ("thisissand", "This is Sand", "https://thisissand.com/", "This is Sand", "Pour. Zoom. Pour."),
    ("linus-rps", "RPS", "https://www.rpsgame.org/", "RPS", "Rock. Paper. The third one."),
    ("geoguessr", "GeoGuessr", "https://www.geoguessr.com/", "GeoGuessr", "Where on earth."),
    ("cityguessr", "City Guesser", "https://cityguessr.com/", "CityGuessr", "A moving street, a guess."),
    ("timeguessr", "TimeGuessr", "https://timeguessr.com/", "TimeGuessr", "When, not just where."),
    ("worldle", "Worldle", "https://worldle.teuteuf.fr/", "Teuteuf", "Wordle, but maps."),
    ("travle", "Travle", "https://travle.earth/", "Travle", "Border by border."),
    ("framed", "Framed", "https://framed.wtf/", "Framed", "One still. Name the film."),
    ("heardle", "Heardle", "https://heardlewordle.io/", "Heardle", "One note. Name the song."),
    ("connections", "Connections", "https://www.nytimes.com/games/connections", "NYT", "Four groups. One headache."),
    ("strands", "Strands", "https://www.nytimes.com/games/strands", "NYT", "The other word hunt."),
    ("pips", "Pips", "https://www.nytimes.com/games/pips", "NYT", "Dominoes, NYT-ified."),
    ("sudoku-nyt", "NYT Sudoku", "https://www.nytimes.com/puzzles/sudoku", "NYT", "Nines in a square."),
    ("spellingbee", "Spelling Bee", "https://www.nytimes.com/puzzles/spelling-bee", "NYT", "Pangrams for the proud."),
    ("letterboxed", "Letter Boxed", "https://www.nytimes.com/puzzles/letter-boxed", "NYT", "Sides of a square."),
    ("themini", "The Mini", "https://www.nytimes.com/crosswords/game/mini", "NYT", "Five minutes, allegedly."),
    ("crazymonkey", "Crazy Monkey Games", "https://www.crazymonkeygames.com/", "CMG", "Flash’s grandchildren."),
    ("addicting", "Addicting Games", "https://www.addictinggames.com/", "AG", "The name was a warning."),
    ("kongregate", "Kongregate", "https://www.kongregate.com/", "Kongregate", "The portal that stayed."),
    ("newgrounds", "Newgrounds", "https://www.newgrounds.com/", "Newgrounds", "The internet’s basement, still open."),
    ("armorgames", "Armor Games", "https://armorgames.com/", "Armor", "Stick figures with lore."),
    ("coolmath2", "Coolmath Games", "https://www.coolmathgames.com/", "Coolmath", "Educational. Sure."),
    ("mathplayground", "Math Playground", "https://www.mathplayground.com/", "Math Playground", "Teachers allow this one."),
    ("primarygames", "PrimaryGames", "https://www.primarygames.com/", "PrimaryGames", "Classroom-safe chaos."),
    ("pogo", "Pogo", "https://www.pogo.com/", "EA", "The old lobby."),
    ("solitaire-google", "Google Solitaire", "https://www.google.com/logos/fnbx/solitaire/standalone.html", "Google", "The doodle that stayed."),
    ("minesweeper-google", "Google Minesweeper", "https://www.google.com/fbx/minesweeper", "Google", "Still one wrong click."),
    ("pacman-google", "Google Pac-Man", "https://www.google.com/logos/2010/pacman10-i.html", "Google", "The doodle that ate an afternoon."),
    ("tetris", "Tetris", "https://tetris.com/play-tetris", "Tetris", "The blocks. Official-ish."),
    ("jstris", "Jstris", "https://jstris.jezevec10.com/", "Jstris", "Competitive falling squares."),
    ("tetrio", "TETR.IO", "https://tetr.io/", "osk", "The modern brick pit."),
    ("n-gon", "n-gon", "https://landgreen.github.io/n-gon/", "Landgreen", "A physics shooter in a tab."),
    ("underrun", "Underrun", "https://phoboslab.org/underrun/", "Phoboslab", "A tiny 3D that shouldn’t exist."),
    ("voidwasteland", "Void", "https://phoboslab.org/void/", "Phoboslab", "More from the same basement."),
    ("q1k3", "Q1K3", "https://js13kgames.com/games/q1k3/index.html", "js13k", "Quake, 13 kilobytes."),
    ("js13k", "js13kGames", "https://js13kgames.com/", "js13k", "Games that fit in a tweet."),
    ("webgl-fluid", "WebGL Fluid", "https://paveldogreat.github.io/WebGL-Fluid-Simulation/", "Pavel", "Poke the universe."),
    ("windows93", "Windows 93", "https://www.windows93.net/", "Windows93", "The OS that shouldn’t."),
    ("98.js", "98.js", "https://98.js.org/", "1j01", "A desktop in the tab."),
    ("win11-web", "Windows 11 Web", "https://win11.blueedge.me/", "Blue Edge", "The other desktop."),
    ("macos-web", "macOS Web", "https://macos-web.app/", "Puru", "Traffic lights, in HTML."),
    ("ubuntu-web", "Ubuntu Tour", "https://www.youtube.com/ubuntu/", "Canonical", "A tour. Sort of."),
    ("copy-sh", "copy.sh v86", "https://copy.sh/v86/", "copy.sh", "Boot an OS in WASM."),
    ("itch", "itch.io", "https://itch.io/", "itch.io", "The indie shelf."),
    ("gamejolt", "Game Jolt", "https://gamejolt.com/", "Game Jolt", "The other indie shelf."),
    ("crazygames", "CrazyGames", "https://www.crazygames.com/", "CrazyGames", "The arcade that never closed."),
    ("poki2", "Poki", "https://poki.com/", "Poki", "Instant. Again."),
    ("iogames", "IO Games", "https://iogames.space/", "IO", "The .io directory."),
    ("twoplayer", "2 Player Games", "https://www.twoplayergames.org/", "2PG", "One keyboard. Two grudges."),
    ("y8", "Y8", "https://www.y8.com/", "Y8", "The portal from 2008, still."),
    ("friv", "Friv", "https://www.friv.com/", "Friv", "School computer folklore."),
    ("miniclip", "Miniclip", "https://www.miniclip.com/", "Miniclip", "8 Ball Pool’s house."),
    ("8ball", "8 Ball Pool", "https://miniclip.com/games/8-ball-pool-multiplayer/en/", "Miniclip", "The cue in a tab."),
    ("chess-lichess-tv", "Lichess TV", "https://lichess.org/tv", "Lichess", "Watch someone blunder live."),
    ("paperio", "paper.io", "https://paper-io.com/", "Voodoo", "Claim the floor."),
    ("holeio", "Hole.io", "https://hole-io.com/", "Voodoo", "Eat the city."),
    ("skribbl", "skribbl.io", "https://skribbl.io/", "Skribbl", "Draw. Lie. Guess."),
    ("gartic", "Gartic Phone", "https://garticphone.com/", "Gartic", "Telephone, but pictures."),
    ("jackbox", "Jackbox.tv", "https://jackbox.tv/", "Jackbox", "The phone is the controller."),
    ("kahoot", "Kahoot!", "https://kahoot.it/", "Kahoot", "The classroom buzzer."),
    ("blooket", "Blooket", "https://play.blooket.com/", "Blooket", "The other classroom buzzer."),
    ("gimkit", "Gimkit", "https://www.gimkit.com/", "Gimkit", "Quiz with a shop."),
    ("quizizz", "Quizizz", "https://quizizz.com/", "Quizizz", "Homework, gamified."),
    ("wordwall", "Wordwall", "https://wordwall.net/", "Wordwall", "Teachers’ toybox."),
    ("geogebra", "GeoGebra", "https://www.geogebra.org/", "GeoGebra", "Math you can drag."),
    ("wolframalpha", "WolframAlpha", "https://www.wolframalpha.com/", "Wolfram", "Ask the engine."),
    ("oeis", "OEIS", "https://oeis.org/", "OEIS", "Integer sequences, all of them."),
    ("puzzling-se", "Puzzling Stack", "https://puzzling.stackexchange.com/", "Stack Exchange", "Riddles with comments."),
    ("codewars", "Codewars", "https://www.codewars.com/", "Codewars", "Katas for the keyboard."),
    ("hackerrank", "HackerRank", "https://www.hackerrank.com/", "HackerRank", "The interview gym."),
    ("exercism", "Exercism", "https://exercism.org/", "Exercism", "Mentored drills."),
    ("frontendmentor", "Frontend Mentor", "https://www.frontendmentor.io/", "FEM", "Copy the screenshot. Ship it."),
    ("cssbattle", "CSSBattle", "https://cssbattle.dev/", "CSSBattle", "Pixels as sport."),
    ("flexboxfroggy", "Flexbox Froggy", "https://flexboxfroggy.com/", "Codepip", "Frogs, aligned."),
    ("gridgarden", "Grid Garden", "https://cssgridgarden.com/", "Codepip", "Carrots, gridded."),
    ("screeps", "Screeps", "https://screeps.com/", "Screeps", "An MMO you program."),
    ("coderbyte", "Coderbyte", "https://coderbyte.com/", "Coderbyte", "Challenges, timed."),
    ("edabit", "Edabit", "https://edabit.com/", "Edabit", "Bites of code."),
    ("sqlbolt", "SQLBolt", "https://sqlbolt.com/", "SQLBolt", "Learn SQL by doing it."),
    ("sql-island", "SQL Island", "https://sql-island.informatik.uni-kl.de/", "Uni KL", "A quest with SELECT."),
    ("overthewire", "OverTheWire", "https://overthewire.org/wargames/", "OTW", "Wargames in a browser."),
    ("crypto-pals", "Cryptopals", "https://cryptopals.com/", "Cryptopals", "Break crypto, on purpose."),
    ("picoctf", "picoCTF", "https://picoctf.org/", "CMU", "Capture the flag, politely."),
]
for i, n, u, d, t in games:
    g = "games"
    if i in ("geogebra", "wolframalpha", "oeis", "sqlbolt", "flexboxfroggy", "gridgarden"):
        g = "education,games"
    add(i, n, u, d, g, t)

# --- Tools ---
tools = [
    ("jsonlint", "JSONLint", "https://jsonlint.com/", "JSONLint", "Paste. It yells."),
    ("jsonformatter", "JSON Formatter", "https://jsonformatter.org/", "JSONformatter", "Pretty, finally."),
    ("jsoneditoronline", "JSON Editor Online", "https://jsoneditoronline.org/", "JSON Editor", "A tree for your blob."),
    ("jwt-io", "jwt.io", "https://jwt.io/", "Auth0", "Decode the token you shouldn’t have pasted."),
    ("regexr", "RegExr", "https://regexr.com/", "RegExr", "The other regex playground."),
    ("regex-vis", "Regex Vis", "https://regex-vis.com/", "RegexVis", "See the machine."),
    ("crontab-guru", "crontab guru", "https://crontab.guru/", "Cronitor", "Five stars, explained."),
    ("caniuse", "Can I use", "https://caniuse.com/", "Caniuse", "The compatibility bible."),
    ("mdn-play", "MDN Playground", "https://developer.mozilla.org/en-US/play", "Mozilla", "Try the snippet."),
    ("codepen-new", "CodePen", "https://codepen.io/pen/", "CodePen", "A front-end scratchpad."),
    ("jsfiddle", "JSFiddle", "https://jsfiddle.net/", "JSFiddle", "The older scratchpad."),
    ("jsbin", "JS Bin", "https://jsbin.com/", "JS Bin", "Older still."),
    ("sqlfiddle", "SQL Fiddle", "https://sqlfiddle.com/", "SQL Fiddle", "A database in a paste."),
    ("db-fiddle", "DB Fiddle", "https://www.db-fiddle.com/", "DB Fiddle", "The other SQL paste."),
    ("explain-pg", "Explain PostgreSQL", "https://explain.dalibo.com/", "Dalibo", "Plans, drawn."),
    ("swagger-editor", "Swagger Editor", "https://editor.swagger.io/", "SmartBear", "OpenAPI, live."),
    ("hoppscotch", "Hoppscotch", "https://hoppscotch.io/", "Hoppscotch", "Postman that stayed in the tab."),
    ("httpie", "HTTPie", "https://httpie.io/app", "HTTPie", "Pretty requests."),
    ("reqbin", "ReqBin", "https://reqbin.com/", "ReqBin", "Hit an endpoint."),
    ("webhook-site", "Webhook.site", "https://webhook.site/", "Webhook.site", "Catch the POST."),
    ("ngrok-status", "ngrok", "https://ngrok.com/", "ngrok", "A tunnel, documented."),
    ("carbon", "Carbon", "https://carbon.now.sh/", "Carbon", "Make the snippet look expensive."),
    ("ray-so", "ray.so", "https://ray.so/", "Raycast", "The other pretty snippet."),
    ("chalk-shot", "Chalk.ist", "https://chalk.ist/", "Chalk", "Yet another pretty snippet."),
    ("excalidraw-plus", "Excalidraw+", "https://plus.excalidraw.com/", "Excalidraw", "The whiteboard, with a plus."),
    ("tldraw", "tldraw", "https://www.tldraw.com/", "tldraw", "The other infinite canvas."),
    ("eraser", "Eraser", "https://app.eraser.io/", "Eraser", "Diagrams from a sentence."),
    ("whimsical", "Whimsical", "https://whimsical.com/", "Whimsical", "Pretty boxes."),
    ("lucidchart", "Lucidchart", "https://www.lucidchart.com/", "Lucid", "The enterprise whiteboard."),
    ("drawsql", "DrawSQL", "https://drawsql.app/", "DrawSQL", "Schemas, drawn."),
    ("dbdiagram", "dbdiagram.io", "https://dbdiagram.io/", "holistics", "Tables with lines."),
    ("sql-schema", "SQL Schema", "https://sqlschema.com/", "SQL Schema", "Yet more boxes."),
    ("mermaid-live", "Mermaid Live", "https://mermaid.live/", "Mermaid", "Text in. Chart out."),
    ("plantuml", "PlantUML", "https://www.plantuml.com/plantuml/uml/", "PlantUML", "Old reliable diagrams."),
    ("structurizr", "Structurizr", "https://structurizr.com/", "Structurizr", "C4, in a tab."),
    ("markmap", "Markmap", "https://markmap.js.org/repl", "Markmap", "Markdown as a mind map."),
    ("obsidian-publish", "Obsidian Publish", "https://publish.obsidian.md/", "Obsidian", "The garden, public."),
    ("logseq", "Logseq", "https://logseq.com/", "Logseq", "Outliner brain."),
    ("anytype", "Anytype", "https://anytype.io/", "Anytype", "Local-first notes."),
    ("capacities", "Capacities", "https://capacities.io/", "Capacities", "Objects, not pages."),
    ("craft", "Craft", "https://docs.craft.do/", "Craft", "Pretty documents."),
    ("coda", "Coda", "https://coda.io/", "Coda", "Docs that act like apps."),
    ("airtable", "Airtable", "https://airtable.com/", "Airtable", "The spreadsheet that grew up."),
    ("baserow", "Baserow", "https://baserow.io/", "Baserow", "Airtable’s open cousin."),
    ("nocodb", "NocoDB", "https://www.nocodb.com/", "NocoDB", "Airtable on your own tables."),
    ("notion-calendar", "Notion Calendar", "https://calendar.notion.so/", "Notion", "The other calendar."),
    ("cron-calendar", "Cron", "https://cron.com/", "Notion", "The calendar Notion bought."),
    ("sunsama", "Sunsama", "https://www.sunsama.com/", "Sunsama", "A calmer day."),
    ("akiflow", "Akiflow", "https://akiflow.com/", "Akiflow", "Tasks from everywhere."),
    ("todoist", "Todoist", "https://todoist.com/", "Doist", "The list that nagged you first."),
    ("ticktick", "TickTick", "https://ticktick.com/", "TickTick", "Tasks plus a pomodoro."),
    ("microsoft-todo", "Microsoft To Do", "https://to-do.office.com/", "Microsoft", "Wunderlist’s ghost."),
    ("anydo", "Any.do", "https://www.any.do/", "Any.do", "The other list."),
    ("thingscloud", "Things", "https://culturedcode.com/things/", "Cultured Code", "Mostly a site. Still pretty."),
    ("omnifocus", "OmniFocus", "https://www.omnigroup.com/omnifocus/", "Omni", "GTD, billed."),
    ("workflowy", "WorkFlowy", "https://workflowy.com/", "WorkFlowy", "One infinite bullet."),
    ("dynalist", "Dynalist", "https://dynalist.io/", "Dynalist", "The other infinite bullet."),
    ("checkvist", "Checkvist", "https://checkvist.com/", "Checkvist", "Keyboard-first lists."),
    ("standardnotes", "Standard Notes", "https://app.standardnotes.com/", "Standard Notes", "Notes that don’t read you."),
    ("cryptpad", "CryptPad", "https://cryptpad.fr/", "XWiki", "Zero-knowledge office."),
    ("privnote", "Privnote", "https://privnote.com/", "Privnote", "A note that burns."),
    ("protectedtext", "ProtectedText", "https://www.protectedtext.com/", "ProtectedText", "Encrypted notepad, no account."),
    ("onlinenotepad", "Online Notepad", "https://onlinenotepad.org/", "Online Notepad", "The blank page."),
    ("notepad-pw", "notepad.pw", "https://notepad.pw/", "notepad.pw", "A URL that is a page."),
    ("shrib", "shrib", "https://shrib.com/", "shrib", "A note at a name."),
    ("hackmd", "HackMD", "https://hackmd.io/", "HackMD", "Markdown, together."),
    ("hedgedoc", "HedgeDoc", "https://demo.hedgedoc.org/", "HedgeDoc", "The community markdown room."),
    ("stackedit", "StackEdit", "https://stackedit.io/", "StackEdit", "Markdown with a preview."),
    ("dillinger", "Dillinger", "https://dillinger.io/", "Dillinger", "The other markdown tab."),
    ("ghost-org", "Ghost", "https://ghost.org/", "Ghost", "Publishing, not a social network."),
    ("write-as", "Write.as", "https://write.as/", "Write.as", "A quieter post."),
    ("bearblog", "Bear Blog", "https://bearblog.dev/", "Bear", "A blog with almost nothing."),
    ("neocities", "Neocities", "https://neocities.org/", "Neocities", "GeoCities’ honest child."),
    ("tilde", "tilde.town", "https://tilde.town/", "tilde", "A unix pub."),
    ("omni", "Omnivore", "https://omnivore.app/", "Omnivore", "Read it later, open source."),
    ("instapaper", "Instapaper", "https://www.instapaper.com/", "Instapaper", "The original later."),
    ("pocket", "Pocket", "https://getpocket.com/", "Mozilla", "The pocket Mozilla kept."),
    ("raindrop", "Raindrop.io", "https://raindrop.io/", "Raindrop", "Bookmarks with taste."),
    ("pinboard", "Pinboard", "https://pinboard.in/", "Pinboard", "Bookmarks for adults."),
    ("are-na", "Are.na", "https://www.are.na/", "Are.na", "Mood boards with a brain."),
    ("cosmos", "Cosmos", "https://www.cosmos.so/", "Cosmos", "A visual library."),
    ("savee", "Savee", "https://savee.it/", "Savee", "References, hoarded."),
    ("pinterest-today", "Pinterest Today", "https://www.pinterest.com/today/", "Pinterest", "The feed of wants."),
    ("tinyurl", "TinyURL", "https://tinyurl.com/", "TinyURL", "The original shortener."),
    ("bitly", "Bitly", "https://bitly.com/", "Bitly", "The corporate shortener."),
    ("dub", "Dub", "https://dub.co/", "Dub", "The modern shortener."),
    ("rebrandly", "Rebrandly", "https://www.rebrandly.com/", "Rebrandly", "Branded links."),
    ("qr-code-gen", "QR Code Generator", "https://www.qr-code-generator.com/", "QR", "A square for the camera."),
    ("the-qr", "QRCode Monkey", "https://www.qrcode-monkey.com/", "Monkey", "A prettier square."),
    ("tinywow", "TinyWow", "https://tinywow.com/", "TinyWow", "A tool shed."),
    ("ilovepdf", "iLovePDF", "https://www.ilovepdf.com/", "iLovePDF", "The PDF that needed a hug."),
    ("smallpdf", "Smallpdf", "https://smallpdf.com/", "Smallpdf", "Compress, merge, survive."),
    ("pdf24", "PDF24", "https://tools.pdf24.org/", "PDF24", "The German toolbox."),
    ("sejda", "Sejda", "https://www.sejda.com/", "Sejda", "PDF, in the browser."),
    ("combinepdf", "CombinePDF", "https://combinepdf.com/", "CombinePDF", "One job."),
    ("extractpdf", "ExtractPDF", "https://www.extractpdf.com/", "ExtractPDF", "The other job."),
    ("remove-bg-alt", "Adobe Express remove.bg", "https://www.adobe.com/express/feature/image/remove-background", "Adobe", "The other background leave."),
    ("photoroom", "Photoroom", "https://www.photoroom.com/", "Photoroom", "Product shots, instantly."),
    ("cleanup-pictures", "cleanup.pictures", "https://cleanup.pictures/", "Cleanup", "Erase the tourist."),
    ("clipdrop", "Clipdrop", "https://clipdrop.co/", "Stability", "Magic eraser energy."),
    ("magnific", "Magnific", "https://magnific.ai/", "Magnific", "Upscale, dramatically."),
    ("upscayl-web", "Upscayl", "https://upscayl.org/", "Upscayl", "The open upscaler."),
    ("waifu2x", "waifu2x", "https://waifu2x.udp.jp/", "nagadomi", "Anime, larger."),
    ("tinypng", "TinyPNG", "https://tinypng.com/", "TinyPNG", "Crush the PNG."),
    ("tinyjpg", "TinyJPG", "https://tinyjpg.com/", "TinyPNG", "Crush the JPG."),
    ("svgomg2", "SVGOMG", "https://jakearchibald.github.io/svgomg/", "Jake Archibald", "Jake’s SVG diet."),
    ("vecta", "Vecta Nano", "https://vecta.io/nano", "Vecta", "SVG, smaller."),
    ("base64-image", "Base64 Image", "https://www.base64-image.de/", "base64", "A picture, as text."),
    ("cloudconvert", "CloudConvert", "https://cloudconvert.com/", "CloudConvert", "Anything to anything."),
    ("zamzar", "Zamzar", "https://www.zamzar.com/", "Zamzar", "The original converter."),
    ("online-convert", "Online-Convert", "https://www.online-convert.com/", "OC", "The other converter."),
    ("convertio", "Convertio", "https://convertio.co/", "Convertio", "Yet another converter."),
    ("ezgif", "EZGIF", "https://ezgif.com/", "EZGIF", "GIF surgery."),
    ("gifmaker", "Gifmaker", "https://gifmaker.me/", "Gifmaker", "Frames into a loop."),
    ("kapwing", "Kapwing", "https://www.kapwing.com/", "Kapwing", "Meme workshop."),
    ("canva-magic", "Canva Magic", "https://www.canva.com/magic-studio/", "Canva", "The studio inside the studio."),
    ("visme", "Visme", "https://www.visme.co/", "Visme", "The other pretty deck."),
    ("pitch", "Pitch", "https://pitch.com/", "Pitch", "Slides that feel like 2024."),
    ("gamma", "Gamma", "https://gamma.app/", "Gamma", "A deck from a paragraph."),
    ("plusai", "Plus AI", "https://plusdocs.com/", "Plus", "Slides, assisted."),
    ("beautiful-ai", "Beautiful.ai", "https://www.beautiful.ai/", "Beautiful", "The name is the pitch."),
    ("prezi", "Prezi", "https://prezi.com/", "Prezi", "The zooming deck."),
    ("google-slides", "Google Slides", "https://slides.google.com/", "Google", "The deck everyone has."),
    ("google-forms", "Google Forms", "https://forms.google.com/", "Google", "A survey in a minute."),
    ("typeform", "Typeform", "https://www.typeform.com/", "Typeform", "One question at a time."),
    ("tally", "Tally", "https://tally.so/", "Tally", "Forms that don’t look like forms."),
    ("fillout", "Fillout", "https://www.fillout.com/", "Fillout", "The other pretty form."),
    ("jotform", "Jotform", "https://www.jotform.com/", "Jotform", "The form factory."),
    ("microsoft-forms", "Microsoft Forms", "https://forms.office.com/", "Microsoft", "The office survey."),
    ("surveymonkey", "SurveyMonkey", "https://www.surveymonkey.com/", "SurveyMonkey", "The original ask."),
    ("qualtrics", "Qualtrics", "https://www.qualtrics.com/", "Qualtrics", "Enterprise feelings."),
]
for i, n, u, d, t in tools:
    add(i, n, u, d, "tools", t)


# --- Shopping / food / travel / finance / health / music / video / edu / social ---
shopping = [
    ("target", "Target", "https://www.target.com/", "Target", "shopping", "The red dot."),
    ("walmart", "Walmart", "https://www.walmart.com/", "Walmart", "shopping", "The big box, in a tab."),
    ("costco", "Costco", "https://www.costco.com/", "Costco", "shopping", "A membership and a hot dog."),
    ("bestbuy", "Best Buy", "https://www.bestbuy.com/", "Best Buy", "shopping", "The blue shirt, online."),
    ("homedepot", "Home Depot", "https://www.homedepot.com/", "Home Depot", "shopping", "Orange. Aisle 12."),
    ("lowes", "Lowe’s", "https://www.lowes.com/", "Lowe’s", "shopping", "The other orange."),
    ("ikea-us", "IKEA US", "https://www.ikea.com/us/en/", "IKEA", "shopping", "The warehouse, localized."),
    ("wayfair", "Wayfair", "https://www.wayfair.com/", "Wayfair", "shopping", "A sofa, eventually."),
    ("overstock", "Overstock", "https://www.overstock.com/", "Overstock", "shopping", "The leftover aisle."),
    ("wayfair-ca", "Wayfair CA", "https://www.wayfair.ca/", "Wayfair", "shopping", "Canada’s leftover aisle."),
    ("zara", "Zara", "https://www.zara.com/", "Inditex", "shopping", "Fast. Fashion."),
    ("hm", "H&M", "https://www.hm.com/", "H&M", "shopping", "The other fast."),
    ("uniqlo", "UNIQLO", "https://www.uniqlo.com/", "Fast Retailing", "shopping,lifestyle", "Heattech, explained."),
    ("nike", "Nike", "https://www.nike.com/", "Nike", "shopping", "Just the store."),
    ("adidas", "adidas", "https://www.adidas.com/", "adidas", "shopping", "The three stripes."),
    ("lululemon", "lululemon", "https://shop.lululemon.com/", "lululemon", "shopping,lifestyle", "Yoga, as retail."),
    ("rei", "REI", "https://www.rei.com/", "REI", "shopping,travel", "The co-op."),
    ("patagonia", "Patagonia", "https://www.patagonia.com/", "Patagonia", "shopping,lifestyle", "Don’t buy this jacket. Anyway."),
    ("nordstrom", "Nordstrom", "https://www.nordstrom.com/", "Nordstrom", "shopping", "The piano, elsewhere."),
    ("macys", "Macy’s", "https://www.macys.com/", "Macy’s", "shopping", "The balloon people."),
    ("kohls", "Kohl’s", "https://www.kohls.com/", "Kohl’s", "shopping", "Kohl’s cash, forever."),
    ("sephora", "Sephora", "https://www.sephora.com/", "Sephora", "shopping,lifestyle", "The black-and-white aisle."),
    ("ulta", "Ulta", "https://www.ulta.com/", "Ulta", "shopping,lifestyle", "The other aisle."),
    ("glossier", "Glossier", "https://www.glossier.com/", "Glossier", "shopping,lifestyle", "Pink, as a brand."),
    ("etsy2", "Etsy", "https://www.etsy.com/", "Etsy", "shopping", "Handmade, allegedly."),
    ("ebay", "eBay", "https://www.ebay.com/", "eBay", "shopping", "Auctions that never died."),
    ("poshmark", "Poshmark", "https://poshmark.com/", "Poshmark", "shopping", "The closet, listed."),
    ("depop", "Depop", "https://www.depop.com/", "Depop", "shopping", "The cooler closet."),
    ("grailed", "Grailed", "https://www.grailed.com/", "Grailed", "shopping", "Hype, secondhand."),
    ("stockx", "StockX", "https://stockx.com/", "StockX", "shopping", "The stock market for shoes."),
    ("goat", "GOAT", "https://www.goat.com/", "GOAT", "shopping", "The other shoe market."),
    ("discogs", "Discogs", "https://www.discogs.com/", "Discogs", "shopping,music", "Vinyl, catalogued."),
    ("bandcamp-daily", "Bandcamp Daily", "https://daily.bandcamp.com/", "Bandcamp", "music,news", "The desk that pays artists."),
    ("aliexpress", "AliExpress", "https://www.aliexpress.com/", "Alibaba", "shopping", "A warehouse with a delay."),
    ("alibaba", "Alibaba", "https://www.alibaba.com/", "Alibaba", "shopping,business", "The factory floor."),
    ("temu", "Temu", "https://www.temu.com/", "PDD", "shopping", "The price is the pitch."),
    ("shein", "SHEIN", "https://www.shein.com/", "SHEIN", "shopping", "The firehose."),
    ("zalando", "Zalando", "https://www.zalando.com/", "Zalando", "shopping", "Europe’s closet."),
    ("asos", "ASOS", "https://www.asos.com/", "ASOS", "shopping", "As seen on screen."),
    ("farfetch", "Farfetch", "https://www.farfetch.com/", "Farfetch", "shopping", "Luxury, aggregated."),
    ("ssense", "SSENSE", "https://www.ssense.com/", "SSENSE", "shopping", "Montreal, expensive."),
    ("endclothing", "END.", "https://www.endclothing.com/", "END", "shopping", "The drop."),
    ("mrporter", "Mr Porter", "https://www.mrporter.com/", "Net-a-Porter", "shopping", "Men, styled."),
    ("netaporter", "Net-a-Porter", "https://www.net-a-porter.com/", "NAP", "shopping", "Women, styled."),
    ("shopify-store", "Shopify", "https://www.shopify.com/", "Shopify", "business,shopping", "The stall for stalls."),
    ("bigcartel", "Big Cartel", "https://www.bigcartel.com/", "Big Cartel", "shopping,business", "The smaller stall."),
    ("gumroad", "Gumroad", "https://gumroad.com/", "Gumroad", "shopping,business", "Sell the file."),
    ("lemon-squeezy", "Lemon Squeezy", "https://www.lemonsqueezy.com/", "Lemon Squeezy", "business", "Merchant of record."),
    ("paddle", "Paddle", "https://www.paddle.com/", "Paddle", "business", "The other merchant."),
    ("stripe-dashboard", "Stripe Dashboard", "https://dashboard.stripe.com/", "Stripe", "finance,business", "The money room."),
]
for i, n, u, d, g, t in shopping:
    add(i, n, u, d, g, t)

food = [
    ("ubereats", "Uber Eats", "https://www.ubereats.com/", "Uber", "food", "Dinner, dispatched. Again."),
    ("grubhub", "Grubhub", "https://www.grubhub.com/", "Grubhub", "food", "The older dispatch."),
    ("postmates", "Postmates", "https://postmates.com/", "Uber", "food", "The brand Uber kept."),
    ("seamless", "Seamless", "https://www.seamless.com/", "Grubhub", "food", "NYC’s other name."),
    ("deliveroo", "Deliveroo", "https://deliveroo.co.uk/", "Deliveroo", "food", "The kangaroo."),
    ("justeat", "Just Eat", "https://www.just-eat.co.uk/", "Just Eat", "food", "UK, hungry."),
    ("lieferando", "Lieferando", "https://www.lieferando.de/", "Just Eat", "food", "Germany, hungry."),
    ("swiggy", "Swiggy", "https://www.swiggy.com/", "Swiggy", "food", "India, dispatched."),
    ("zomato", "Zomato", "https://www.zomato.com/", "Zomato", "food", "India’s other dispatch."),
    ("rappi", "Rappi", "https://www.rappi.com/", "Rappi", "food", "Latin America, dispatched."),
    ("ifood", "iFood", "https://www.ifood.com.br/", "iFood", "food", "Brazil, hungry."),
    ("gopuff", "Gopuff", "https://www.gopuff.com/", "Gopuff", "food,shopping", "Convenience, instantly."),
    ("instacart", "Instacart", "https://www.instacart.com/", "Instacart", "food,shopping", "Someone else’s cart."),
    ("amazon-fresh", "Amazon Fresh", "https://www.amazon.com/alm/storefront?almBrandId=QW1hem9uIEZyZXNo", "Amazon", "food,shopping", "Groceries, Prime."),
    ("walmart-grocery", "Walmart Grocery", "https://www.walmart.com/grocery", "Walmart", "food,shopping", "The aisle, delivered."),
    ("allrecipes", "Allrecipes", "https://www.allrecipes.com/", "Dotdash", "food", "The comments are the recipe."),
    ("foodnetwork", "Food Network", "https://www.foodnetwork.com/", "WBD", "food,entertainment", "The channel, as a site."),
    ("seriouseats", "Serious Eats", "https://www.seriouseats.com/", "SERIOUS EATS", "food", "The science of dinner."),
    ("bonappetit", "Bon Appétit", "https://www.bonappetit.com/", "Condé Nast", "food", "The test kitchen."),
    ("nytcooking", "NYT Cooking", "https://cooking.nytimes.com/", "NYT", "food", "Recipes with a byline."),
    ("budgetbytes", "Budget Bytes", "https://www.budgetbytes.com/", "Budget Bytes", "food", "Dinner for the rest of us."),
    ("smitten", "Smitten Kitchen", "https://smittenkitchen.com/", "SK", "food", "A small kitchen, a lot of butter."),
    ("epicurious", "Epicurious", "https://www.epicurious.com/", "Condé Nast", "food", "The archive."),
    ("yummly", "Yummly", "https://www.yummly.com/", "Yummly", "food", "A fridge, suggested."),
    ("supercook", "SuperCook", "https://www.supercook.com/", "SuperCook", "food", "What’s in the fridge."),
    ("tasty", "Tasty", "https://tasty.co/", "BuzzFeed", "food", "The loop that cooks."),
    ("hellfresh", "HelloFresh", "https://www.hellofresh.com/", "HelloFresh", "food", "A box on Tuesdays."),
    ("blueapron", "Blue Apron", "https://www.blueapron.com/", "Blue Apron", "food", "The other box."),
    ("factor", "Factor", "https://www.factor75.com/", "Factor", "food,health", "Prepared, mostly."),
    ("opentable", "OpenTable", "https://www.opentable.com/", "OpenTable", "food,travel", "A reservation."),
    ("resy", "Resy", "https://resy.com/", "Resy", "food", "The other reservation."),
    ("tock", "Tock", "https://www.exploretock.com/", "Tock", "food", "Tickets for dinner."),
    ("yelp", "Yelp", "https://www.yelp.com/", "Yelp", "food,maps", "Opinions about the soup."),
    ("happycow", "HappyCow", "https://www.happycow.net/", "HappyCow", "food", "Plants, mapped."),
    ("infatuation", "The Infatuation", "https://www.theinfatuation.com/", "Infatuation", "food", "Reviews with a scale."),
    ("eater", "Eater", "https://www.eater.com/", "Vox", "food,news", "The food desk."),
]
for i, n, u, d, g, t in food:
    add(i, n, u, d, g, t)

travel = [
    ("expedia", "Expedia", "https://www.expedia.com/", "Expedia", "travel", "A bundle."),
    ("kayak", "KAYAK", "https://www.kayak.com/", "KAYAK", "travel", "The search for the seat."),
    ("skyscanner", "Skyscanner", "https://www.skyscanner.com/", "Skyscanner", "travel", "Everywhere, cheapest."),
    ("google-flights", "Google Flights", "https://www.google.com/travel/flights", "Google", "travel", "The graph of prices."),
    ("google-hotels", "Google Hotels", "https://www.google.com/travel/hotels", "Google", "travel", "A bed, graphed."),
    ("hotels", "Hotels.com", "https://www.hotels.com/", "Expedia", "travel", "The night free, eventually."),
    ("hotwire", "Hotwire", "https://www.hotwire.com/", "Expedia", "travel", "Mystery hotel."),
    ("priceline", "Priceline", "https://www.priceline.com/", "Booking", "travel", "Name your price, grandpa."),
    ("agoda", "Agoda", "https://www.agoda.com/", "Booking", "travel", "Asia, booked."),
    ("vrbo", "Vrbo", "https://www.vrbo.com/", "Expedia", "travel", "Someone’s house."),
    ("airbnb2", "Airbnb", "https://www.airbnb.com/", "Airbnb", "travel", "Someone’s house, branded."),
    ("turo", "Turo", "https://turo.com/", "Turo", "travel", "Someone’s car."),
    ("getaround", "Getaround", "https://www.getaround.com/", "Getaround", "travel", "The other car."),
    ("lyft", "Lyft", "https://www.lyft.com/", "Lyft", "travel,maps", "The pink mustache, remembered."),
    ("citymapper", "Citymapper", "https://citymapper.com/", "Citymapper", "maps,travel", "The better transit brain."),
    ("transit", "Transit", "https://transitapp.com/", "Transit", "maps,travel", "The other better brain."),
    ("rome2rio", "Rome2Rio", "https://www.rome2rio.com/", "Rome2Rio", "travel,maps", "How to get there, really."),
    ("rome2rio-app", "Rome2Rio search", "https://www.rome2rio.com/map/", "Rome2Rio", "maps", "The map of means."),
    ("parkrun", "parkrun", "https://www.parkrun.com/", "parkrun", "health,travel", "Saturday, 5K, everywhere."),
    ("alltrails2", "AllTrails", "https://www.alltrails.com/", "AllTrails", "travel,health,maps", "A hike with a battery."),
    ("komoot", "Komoot", "https://www.komoot.com/", "Komoot", "travel,health,maps", "The European trail."),
    ("strava-maps", "Strava maps", "https://www.strava.com/maps", "Strava", "maps,health", "Heatmaps of showing off."),
    ("gaiagps", "Gaia GPS", "https://www.gaiagps.com/", "Outside", "maps,travel", "Topo, in a tab."),
    ("caltopo", "Caltopo", "https://caltopo.com/", "Caltopo", "maps", "The serious map."),
    ("onx", "onX", "https://www.onxmaps.com/", "onX", "maps,travel", "Hunt, hike, property lines."),
    ("windy", "Windy", "https://www.windy.com/", "Windy", "weather,maps", "The beautiful storm."),
    ("zoom-earth", "Zoom Earth", "https://zoom.earth/", "Zoom Earth", "weather,maps", "The planet, now."),
    ("nullschool", "earth.nullschool", "https://earth.nullschool.net/", "nullschool", "weather,maps", "Wind as a painting."),
    ("ventusky", "Ventusky", "https://www.ventusky.com/", "Ventusky", "weather,maps", "The other painting."),
    ("accuweather", "AccuWeather", "https://www.accuweather.com/", "AccuWeather", "weather", "The percentage."),
    ("weatherunderground", "Weather Underground", "https://www.wunderground.com/", "WU", "weather", "Personal weather stations."),
    ("bbc-weather", "BBC Weather", "https://www.bbc.com/weather", "BBC", "weather", "The shipping forecast’s cousin."),
    ("metoffice", "Met Office", "https://www.metoffice.gov.uk/", "Met Office", "weather", "UK, official."),
    ("nws", "National Weather Service", "https://www.weather.gov/", "NOAA", "weather", "US, official."),
    ("flightradar", "Flightradar24", "https://www.flightradar24.com/", "FR24", "maps,travel", "Every plane, a dot."),
    ("flightaware", "FlightAware", "https://www.flightaware.com/", "FlightAware", "maps,travel", "The other dots."),
    ("adsb", "ADS-B Exchange", "https://globe.adsbexchange.com/", "ADS-B", "maps", "The unfiltered dots."),
    ("marinetraffic", "MarineTraffic", "https://www.marinetraffic.com/", "MarineTraffic", "maps", "Every ship, a triangle."),
    ("vesselfinder", "VesselFinder", "https://www.vesselfinder.com/", "VesselFinder", "maps", "The other triangles."),
    ("opensky", "OpenSky", "https://opensky-network.org/", "OpenSky", "maps", "Planes, as research."),
    ("seatguru", "SeatGuru", "https://www.seatguru.com/", "TripAdvisor", "travel", "The seat that kicks."),
    ("expertflyer", "ExpertFlyer", "https://www.expertflyer.com/", "ExpertFlyer", "travel", "Award seats, hunted."),
    ("awardwallet", "AwardWallet", "https://awardwallet.com/", "AwardWallet", "travel,finance", "Points, counted."),
    ("pointsyeah", "Points Yeah", "https://pointsyeah.com/", "Points Yeah", "travel", "The hunt, assisted."),
    ("thepointsguy", "The Points Guy", "https://thepointsguy.com/", "TPG", "travel,news", "Miles, as content."),
    ("lonelyplanet", "Lonely Planet", "https://www.lonelyplanet.com/", "LP", "travel", "The book, as a site."),
    ("wikivoyage", "Wikivoyage", "https://www.wikivoyage.org/", "Wikimedia", "travel,libraries", "The free guidebook."),
    ("atlasobscura", "Atlas Obscura", "https://www.atlasobscura.com/", "Atlas Obscura", "travel,education", "The weird place."),
    ("roadtrippers", "Roadtrippers", "https://roadtrippers.com/", "Roadtrippers", "travel,maps", "The long way."),
    ("maps-me", "MAPS.ME", "https://maps.me/", "MAPS.ME", "maps,travel", "Offline, allegedly."),
    ("organicmaps", "Organic Maps", "https://organicmaps.app/", "Organic Maps", "maps,travel", "Maps without the surveillance."),
    ("openstreetmap", "OpenStreetMap", "https://www.openstreetmap.org/", "OSMF", "maps", "The map we made."),
    ("overpass", "Overpass Turbo", "https://overpass-turbo.eu/", "OSM", "maps,tools", "Query the map."),
    ("geohack", "GeoHack", "https://geohack.toolforge.org/", "Wikimedia", "maps,tools", "A coordinate, every way."),
]
for i, n, u, d, g, t in travel:
    add(i, n, u, d, g, t)

print("count", len(ROWS))

music = [
    ("pandora", "Pandora", "https://www.pandora.com/", "SiriusXM", "music", "The algorithm that started it."),
    ("iheart", "iHeartRadio", "https://www.iheart.com/", "iHeart", "music", "Radio, still."),
    ("tunein", "TuneIn", "https://tunein.com/", "TuneIn", "music", "Every station, almost."),
    ("nax", "Naxx", "https://www.naxos.com/", "Naxos", "music", "Classical, catalogued."),
    ("idagio", "IDAGIO", "https://www.idagio.com/", "IDAGIO", "music", "Classical, streaming."),
    ("qobuz", "Qobuz", "https://www.qobuz.com/", "Qobuz", "music", "Hi-res, French."),
    ("tidal", "TIDAL", "https://tidal.com/", "TIDAL", "music", "The other hi-res."),
    ("deezer", "Deezer", "https://www.deezer.com/", "Deezer", "music", "Paris, streaming."),
    ("anghami", "Anghami", "https://www.anghami.com/", "Anghami", "music", "The Arab catalog."),
    ("boomplay", "Boomplay", "https://www.boomplay.com/", "Boomplay", "music", "Africa, streaming."),
    ("jiosaavn", "JioSaavn", "https://www.jiosaavn.com/", "Jio", "music", "India, streaming."),
    ("gaana", "Gaana", "https://gaana.com/", "Gaana", "music", "The other India."),
    ("wynk", "Wynk", "https://wynk.in/", "Airtel", "music", "Yet another India."),
    ("mixcloud", "Mixcloud", "https://www.mixcloud.com/", "Mixcloud", "music", "The mix, hosted."),
    ("hearthis", "hearthis.at", "https://hearthis.at/", "hearthis", "music", "DJs, uploading."),
    ("audiomack", "Audiomack", "https://audiomack.com/", "Audiomack", "music", "The other SoundCloud."),
    ("bandlab2", "BandLab", "https://www.bandlab.com/", "BandLab", "music", "A DAW in the tab."),
    ("soundtrap", "Soundtrap", "https://www.soundtrap.com/", "Spotify", "music,education", "Classroom DAW."),
    ("audiotool", "Audiotool", "https://www.audiotool.com/", "Audiotool", "music", "The modular in a tab."),
    ("splice", "Splice", "https://splice.com/", "Splice", "music", "The sample store."),
    ("looperman", "Looperman", "https://www.looperman.com/", "Looperman", "music", "Loops, free-ish."),
    ("freesound", "Freesound", "https://freesound.org/", "UPF", "music,libraries", "The sound you need."),
    ("bbc-sound", "BBC Sound Effects", "https://sound-effects.bbcrewind.co.uk/", "BBC", "music,libraries", "The archive of noises."),
    ("musopen", "Musopen", "https://musopen.org/", "Musopen", "music,education", "Public domain, performed."),
    ("imslp", "IMSLP", "https://imslp.org/", "IMSLP", "music,libraries", "The sheet music attic."),
    ("musescore", "MuseScore", "https://musescore.com/", "MuseScore", "music", "Scores, shared."),
    ("flat-io", "Flat", "https://flat.io/", "Flat", "music,education", "Notation in the tab."),
    ("noteflight", "Noteflight", "https://www.noteflight.com/", "Hal Leonard", "music,education", "The other notation tab."),
    ("hooktheory", "Hookpad", "https://www.hooktheory.com/hookpad", "Hooktheory", "music,education", "Theory, applied."),
    ("teoria", "teoria", "https://www.teoria.com/", "teoria", "music,education", "Ear training."),
    ("tonegym", "ToneGym", "https://www.tonegym.co/", "ToneGym", "music,education", "Ears, at the gym."),
    ("songsterr", "Songsterr", "https://www.songsterr.com/", "Songsterr", "music", "Tabs that play."),
    ("ultimate-guitar", "Ultimate Guitar", "https://www.ultimate-guitar.com/", "UG", "music", "The tab dump."),
    ("chordify", "Chordify", "https://chordify.net/", "Chordify", "music", "The song, as chords."),
    ("moises", "Moises", "https://moises.ai/", "Moises", "music", "Stems, split."),
    ("lalal", "LALAL.AI", "https://www.lalal.ai/", "LALAL", "music,tools", "The other stem split."),
    ("vocalremover", "Vocal Remover", "https://vocalremover.org/", "VR", "music,tools", "Karaoke, extracted."),
    ("chorus", "Chorus", "https://chorus.fm/", "Chorus", "music,news", "The feed of records."),
    ("pitchfork", "Pitchfork", "https://pitchfork.com/", "Condé Nast", "music,news", "The score."),
    ("stereogum", "Stereogum", "https://www.stereogum.com/", "Stereogum", "music,news", "The other score."),
    ("thefader", "The FADER", "https://www.thefader.com/", "FADER", "music,news", "Culture, louder."),
    ("nme", "NME", "https://www.nme.com/", "NME", "music,news", "The ink that stayed."),
    ("rollingstone", "Rolling Stone", "https://www.rollingstone.com/", "Penske", "music,news", "The magazine."),
    ("billboard", "Billboard", "https://www.billboard.com/", "Billboard", "music,news", "The chart."),
    ("lastfm", "Last.fm", "https://www.last.fm/", "Last.fm", "music", "Scrobbles, still."),
    ("musicbrainz", "MusicBrainz", "https://musicbrainz.org/", "MetaBrainz", "music,libraries", "The open discography."),
    ("rateyourmusic", "Rate Your Music", "https://rateyourmusic.com/", "Sonemic", "music,libraries", "The nerd shelf."),
    ("albumoftheyear", "AOTY", "https://www.albumoftheyear.org/", "AOTY", "music", "The other nerd shelf."),
    ("genius", "Genius", "https://genius.com/", "Genius", "music,education", "The lyrics, annotated."),
    ("musixmatch", "Musixmatch", "https://www.musixmatch.com/", "Musixmatch", "music", "The other lyrics."),
]
for i, n, u, d, g, t in music:
    add(i, n, u, d, g, t)

video = [
    ("vimeo", "Vimeo", "https://vimeo.com/", "Vimeo", "video", "The other tube."),
    ("dailymotion", "Dailymotion", "https://www.dailymotion.com/", "Dailymotion", "video", "France’s tube."),
    ("rumble", "Rumble", "https://rumble.com/", "Rumble", "video", "The other other tube."),
    ("odysee", "Odysee", "https://odysee.com/", "Odysee", "video", "LBRY, as a site."),
    ("peertube", "PeerTube", "https://joinpeertube.org/", "Framasoft", "video", "Federated video."),
    ("nebula", "Nebula", "https://nebula.tv/", "Standard", "video,education", "The creator co-op."),
    ("curiosity", "Curiosity Stream", "https://curiositystream.com/", "Curiosity", "video,education", "Docs, as a service."),
    ("mubi", "MUBI", "https://mubi.com/", "MUBI", "video,entertainment", "A film a day."),
    ("criterion", "Criterion Channel", "https://www.criterionchannel.com/", "Criterion", "video,entertainment", "The closet of cinema."),
    ("kanopy", "Kanopy", "https://www.kanopy.com/", "Kanopy", "video,libraries", "Your library’s films."),
    ("hoopla", "Hoopla", "https://www.hoopladigital.com/", "Midwest Tape", "libraries,video", "The library card, streaming."),
    ("libby", "Libby", "https://libbyapp.com/", "OverDrive", "libraries", "The library card, reading."),
    ("overdrive", "OverDrive", "https://www.overdrive.com/", "OverDrive", "libraries", "The back office."),
    ("archive-tv", "Internet Archive TV", "https://archive.org/details/tv", "Internet Archive", "video,libraries", "The tape room."),
    ("tubi", "Tubi", "https://tubitv.com/", "Fox", "video,entertainment", "Free, with ads."),
    ("pluto", "Pluto TV", "https://pluto.tv/", "Paramount", "video,entertainment", "Live, with ads."),
    ("freevee", "Freevee", "https://www.amazon.com/gp/video/storefront/ref=atv_hm_hom_c_9zpd8e_2_1", "Amazon", "video", "Amazon’s free aisle."),
    ("roku", "Roku Channel", "https://therokuchannel.roku.com/", "Roku", "video,entertainment", "The channel of channels."),
    ("crunchyroll", "Crunchyroll", "https://www.crunchyroll.com/", "Sony", "video,entertainment", "Anime, officially."),
    ("hidive", "HIDIVE", "https://www.hidive.com/", "AMC", "video,entertainment", "The other anime."),
    ("funimation", "Crunchyroll-Funimation", "https://www.funimation.com/", "Sony", "video", "The brand that folded in."),
    ("hulu", "Hulu", "https://www.hulu.com/", "Disney", "video,entertainment", "The other living room."),
    ("disneyplus", "Disney+", "https://www.disneyplus.com/", "Disney", "video,entertainment", "The castle."),
    ("max", "Max", "https://www.max.com/", "WBD", "video,entertainment", "HBO, renamed."),
    ("peacock", "Peacock", "https://www.peacocktv.com/", "NBCU", "video,entertainment", "The bird."),
    ("paramountplus", "Paramount+", "https://www.paramountplus.com/", "Paramount", "video,entertainment", "The mountain."),
    ("appletv", "Apple TV", "https://tv.apple.com/", "Apple", "video,entertainment", "The plus, in a tab."),
    ("espn", "ESPN", "https://www.espn.com/", "Disney", "news,entertainment", "The scoreboard."),
    ("bleacher", "Bleacher Report", "https://bleacherreport.com/", "WBD", "news,entertainment", "Sports, as a feed."),
    ("theathletic", "The Athletic", "https://theathletic.com/", "NYT", "news", "Sports, written."),
    ("rottentomatoes", "Rotten Tomatoes", "https://www.rottentomatoes.com/", "Fandango", "entertainment", "The tomato."),
    ("metacritic", "Metacritic", "https://www.metacritic.com/", "Fandom", "entertainment,games", "The number."),
    ("fandom", "Fandom", "https://www.fandom.com/", "Fandom", "entertainment,libraries", "The wiki of everything."),
    ("tvtropes", "TV Tropes", "https://tvtropes.org/", "TV Tropes", "entertainment,libraries", "You will not leave."),
    ("imdb-pro", "IMDb", "https://www.imdb.com/", "Amazon", "entertainment", "The credits."),
    ("trakt", "Trakt", "https://trakt.tv/", "Trakt", "entertainment", "Scrobble the episode."),
    ("simkl", "SIMKL", "https://simkl.com/", "SIMKL", "entertainment", "The other scrobble."),
    ("justwatch", "JustWatch", "https://www.justwatch.com/", "JustWatch", "entertainment", "Where is it streaming."),
    ("reelgood", "Reelgood", "https://reelgood.com/", "Reelgood", "entertainment", "The other where."),
    ("letterboxd2", "Letterboxd", "https://letterboxd.com/", "Letterboxd", "entertainment,social", "The diary of films."),
]
for i, n, u, d, g, t in video:
    add(i, n, u, d, g, t)

edu = [
    ("coursera", "Coursera", "https://www.coursera.org/", "Coursera", "education", "A course, a certificate."),
    ("edx", "edX", "https://www.edx.org/", "2U", "education", "The other certificate."),
    ("udemy", "Udemy", "https://www.udemy.com/", "Udemy", "education", "Everything, on sale."),
    ("udacity", "Udacity", "https://www.udacity.com/", "Udacity", "education", "Nanodegrees."),
    ("skillshare", "Skillshare", "https://www.skillshare.com/", "Skillshare", "education", "Creative class."),
    ("masterclass", "MasterClass", "https://www.masterclass.com/", "MasterClass", "education,entertainment", "The celebrity syllabus."),
    ("brilliant", "Brilliant", "https://brilliant.org/", "Brilliant", "education", "Math, interactive."),
    ("khanmigo", "Khanmigo", "https://www.khanmigo.ai/", "Khan Academy", "education", "The tutor."),
    ("ck12", "CK-12", "https://www.ck12.org/", "CK-12", "education,kids", "Free textbooks."),
    ("openstax", "OpenStax", "https://openstax.org/", "Rice", "education", "The free textbook."),
    ("mitocw", "MIT OCW", "https://ocw.mit.edu/", "MIT", "education", "The whole catalog, free."),
    ("harvardcs50", "CS50", "https://cs50.harvard.edu/", "Harvard", "education", "This is CS50."),
    ("stanford-online", "Stanford Online", "https://online.stanford.edu/", "Stanford", "education", "The farm, online."),
    ("youtube-learn", "YouTube Learning", "https://www.youtube.com/learning", "Google", "education,video", "Lectures, algorithmically."),
    ("ted", "TED", "https://www.ted.com/", "TED", "education,video", "18 minutes."),
    ("teded", "TED-Ed", "https://ed.ted.com/", "TED", "education,kids", "The animated 18."),
    ("crashcourse", "Crash Course", "https://thecrashcourse.com/", "Complexly", "education,video", "John, hurrying."),
    ("khan-kids", "Khan Academy Kids", "https://learn.khanacademy.org/khan-academy-kids/", "Khan", "kids,education", "The little one."),
    ("abcmouse", "ABCmouse", "https://www.abcmouse.com/", "Age of Learning", "kids,education", "The subscription alphabet."),
    ("pbskids-games", "PBS Kids Games", "https://pbskids.org/games", "PBS", "kids,games", "The allowed site."),
    ("sesame", "Sesame Workshop", "https://www.sesamestreet.org/", "Sesame", "kids,education", "The street."),
    ("nickjr", "Nick Jr.", "https://www.nickjr.com/", "Paramount", "kids,entertainment", "The other street."),
    ("disney-kids", "Disney Games", "https://disneynow.com/games", "Disney", "kids,games", "The castle, as a game."),
    ("scratch-jr", "ScratchJr", "https://www.scratchjr.org/", "MIT", "kids,education", "Blocks, smaller."),
    ("code-org-studio", "Code.org Studio", "https://studio.code.org/", "Code.org", "kids,education", "The hour, extended."),
    ("tynker", "Tynker", "https://www.tynker.com/", "Tynker", "kids,education", "The other blocks."),
    ("hopscotch", "Hopscotch", "https://www.gethopscotch.com/", "Hopscotch", "kids,education", "Coding, colorful."),
    ("lightbot", "Lightbot", "https://lightbot.com/", "Lightbot", "kids,games,education", "A robot, instructed."),
    ("duolingo-math", "Duolingo Math", "https://www.duolingo.com/math", "Duolingo", "education,kids", "The owl, counting."),
    ("duolingo-music", "Duolingo Music", "https://www.duolingo.com/music", "Duolingo", "education,music", "The owl, on a staff."),
    ("memrise", "Memrise", "https://www.memrise.com/", "Memrise", "education", "Memory, palaces."),
    ("ankiweb", "AnkiWeb", "https://ankiweb.net/", "Anki", "education", "The deck that owns you."),
    ("quizlet", "Quizlet", "https://quizlet.com/", "Quizlet", "education", "Flashcards, social."),
    ("brainscape", "Brainscape", "https://www.brainscape.com/", "Brainscape", "education", "Confidence-based cards."),
    ("knowt", "Knowt", "https://knowt.com/", "Knowt", "education", "Notes to cards."),
    ("notion-students", "Notion Students", "https://www.notion.com/product/notion-for-education", "Notion", "education,productivity", "The campus workspace."),
    ("grammarly-go", "Grammarly", "https://app.grammarly.com/", "Grammarly", "productivity,education", "The quieter editor."),
    ("prowritingaid", "ProWritingAid", "https://prowritingaid.com/", "PWA", "productivity,education", "The other quieter editor."),
    ("hemingway", "Hemingway Editor", "https://hemingwayapp.com/", "Hemingway", "tools,education", "Yellow means long."),
    ("languagetool", "LanguageTool", "https://languagetool.org/", "LanguageTool", "tools,education", "Open-ish grammar."),
    ("deepl-write", "DeepL Write", "https://www.deepl.com/write", "DeepL", "tools,education", "Rewrite, German-engineered."),
    ("reverso", "Reverso", "https://www.reverso.net/", "Reverso", "education,tools", "Context, translated."),
    ("linguee", "Linguee", "https://www.linguee.com/", "DeepL", "education,libraries", "The bilingual corpus."),
    ("wordreference", "WordReference", "https://www.wordreference.com/", "WR", "education,libraries", "The forum in the dictionary."),
    ("wiktionary", "Wiktionary", "https://www.wiktionary.org/", "Wikimedia", "libraries,education", "The free dictionary."),
    ("etymonline", "Etymonline", "https://www.etymonline.com/", "Harper", "libraries,education", "Where the word came from."),
    ("onelook", "OneLook", "https://www.onelook.com/", "Datamuse", "libraries,tools", "Every dictionary at once."),
    ("rhymezone", "RhymeZone", "https://www.rhymezone.com/", "Datamuse", "music,tools", "The rhyme."),
    ("datamuse", "Datamuse", "https://www.datamuse.com/", "Datamuse", "tools", "Words, related."),
    ("thesaurus", "Thesaurus.com", "https://www.thesaurus.com/", "Dictionary.com", "libraries", "The other word."),
    ("dictionary", "Dictionary.com", "https://www.dictionary.com/", "Dictionary.com", "libraries", "The word."),
    ("mw", "Merriam-Webster", "https://www.merriam-webster.com/", "MW", "libraries", "Springfield’s dictionary."),
    ("oed", "OED", "https://www.oed.com/", "OUP", "libraries", "The long one."),
    ("jstor", "JSTOR", "https://www.jstor.org/", "ITHAKA", "libraries,education", "The paywall of record."),
    ("scihub-note", "Unpaywall", "https://unpaywall.org/", "OurResearch", "libraries,education", "The legal crack."),
    ("connectedpapers", "Connected Papers", "https://www.connectedpapers.com/", "CP", "education,tools", "A graph of papers."),
    ("semanticscholar", "Semantic Scholar", "https://www.semanticscholar.org/", "AI2", "education,libraries", "Papers, with a brain."),
    ("google-scholar", "Google Scholar", "https://scholar.google.com/", "Google", "education,libraries", "The academic tab."),
    ("pubmed", "PubMed", "https://pubmed.ncbi.nlm.nih.gov/", "NIH", "health,libraries", "The medical index."),
    ("arxiv", "arXiv", "https://arxiv.org/", "Cornell", "education,libraries", "Preprints, daily."),
    ("biorxiv", "bioRxiv", "https://www.biorxiv.org/", "CSHL", "education,health", "Biology, unpublished-yet."),
    ("ssrn", "SSRN", "https://www.ssrn.com/", "Elsevier", "education,libraries", "Social science, early."),
    ("philpapers", "PhilPapers", "https://philpapers.org/", "PhilPapers", "education,libraries", "Philosophy, indexed."),
    ("stanford-plato", "Stanford Encyclopedia", "https://plato.stanford.edu/", "Stanford", "education,libraries", "The honest encyclopedia."),
    ("iep", "Internet Encyclopedia of Philosophy", "https://iep.utm.edu/", "UTM", "education,libraries", "The other honest one."),
]
for i, n, u, d, g, t in edu:
    add(i, n, u, d, g, t)

finance = [
    ("venmo", "Venmo", "https://venmo.com/", "PayPal", "finance", "The social dollar."),
    ("zelle", "Zelle", "https://www.zellepay.com/", "EWS", "finance", "Bank to bank."),
    ("wise", "Wise", "https://wise.com/", "Wise", "finance", "The cheaper wire."),
    ("revolut", "Revolut", "https://www.revolut.com/", "Revolut", "finance", "The neon bank."),
    ("n26", "N26", "https://n26.com/", "N26", "finance", "Berlin’s bank."),
    ("monzo", "Monzo", "https://monzo.com/", "Monzo", "finance", "The coral card."),
    ("chime", "Chime", "https://www.chime.com/", "Chime", "finance", "The fee-less pitch."),
    ("sofi", "SoFi", "https://www.sofi.com/", "SoFi", "finance", "Student loans, rebranded."),
    ("ally", "Ally", "https://www.ally.com/", "Ally", "finance", "A bank without branches."),
    ("capitalone", "Capital One", "https://www.capitalone.com/", "Capital One", "finance", "What’s in your wallet."),
    ("amex", "American Express", "https://www.americanexpress.com/", "Amex", "finance", "Membership has a tab."),
    ("chase", "Chase", "https://www.chase.com/", "JPMorgan", "finance", "The bank."),
    ("bofa", "Bank of America", "https://www.bankofamerica.com/", "BofA", "finance", "The other bank."),
    ("wellsfargo", "Wells Fargo", "https://www.wellsfargo.com/", "Wells", "finance", "The stagecoach."),
    ("fidelity", "Fidelity", "https://www.fidelity.com/", "Fidelity", "finance", "The 401(k)."),
    ("vanguard", "Vanguard", "https://investor.vanguard.com/", "Vanguard", "finance", "The index."),
    ("schwab", "Schwab", "https://www.schwab.com/", "Schwab", "finance", "The other index."),
    ("etrade", "E*TRADE", "https://us.etrade.com/", "Morgan Stanley", "finance", "The baby on the ad."),
    ("webull", "Webull", "https://www.webull.com/", "Webull", "finance", "The other commission-free."),
    ("public", "Public", "https://public.com/", "Public", "finance,social", "Trades, with a feed."),
    ("stocktwits", "Stocktwits", "https://stocktwits.com/", "Stocktwits", "finance,social", "The yell board."),
    ("seekingalpha", "Seeking Alpha", "https://seekingalpha.com/", "SA", "finance,news", "The thesis, posted."),
    ("yahoo-finance", "Yahoo Finance", "https://finance.yahoo.com/", "Yahoo", "finance,news", "The old terminal."),
    ("marketwatch", "MarketWatch", "https://www.marketwatch.com/", "Dow Jones", "finance,news", "The bell."),
    ("investing", "Investing.com", "https://www.investing.com/", "Investing", "finance,news", "The other bell."),
    ("coingecko", "CoinGecko", "https://www.coingecko.com/", "CoinGecko", "finance", "Every coin, a number."),
    ("coinmarketcap", "CoinMarketCap", "https://coinmarketcap.com/", "Binance", "finance", "The other number."),
    ("binance", "Binance", "https://www.binance.com/", "Binance", "finance", "The big book."),
    ("kraken", "Kraken", "https://www.kraken.com/", "Kraken", "finance", "The other book."),
    ("gemini", "Gemini", "https://www.gemini.com/", "Gemini", "finance", "The twins’ exchange."),
    ("rainbow", "Rainbow", "https://rainbow.me/", "Rainbow", "finance", "A prettier wallet."),
    ("metamask-portfolio", "MetaMask Portfolio", "https://portfolio.metamask.io/", "Consensys", "finance", "The fox’s dashboard."),
    ("zapper", "Zapper", "https://zapper.xyz/", "Zapper", "finance", "Every position, one view."),
    ("defillama", "DefiLlama", "https://defillama.com/", "Llama", "finance", "TVL, honestly."),
    ("dune", "Dune", "https://dune.com/", "Dune", "finance,tools", "Onchain, as SQL."),
    ("nansen", "Nansen", "https://www.nansen.ai/", "Nansen", "finance", "Wallets, labeled."),
    ("opensea", "OpenSea", "https://opensea.io/", "OpenSea", "finance,shopping", "The NFT bazaar."),
    ("blur", "Blur", "https://blur.io/", "Blur", "finance,shopping", "The other bazaar."),
    ("etherscan", "Etherscan", "https://etherscan.io/", "Etherscan", "finance,tools", "The chain, readable."),
    ("solscan", "Solscan", "https://solscan.io/", "Solscan", "finance,tools", "The other chain, readable."),
    ("mint", "Mint", "https://mint.intuit.com/", "Intuit", "finance", "The budget that closed."),
    ("monarch", "Monarch Money", "https://www.monarchmoney.com/", "Monarch", "finance", "The Mint replacement."),
    ("ynab", "YNAB", "https://www.ynab.com/", "YNAB", "finance", "Give every dollar a job."),
    ("empower", "Empower", "https://www.empower.com/", "Empower", "finance", "Net worth, graphed."),
    ("creditkarma", "Credit Karma", "https://www.creditkarma.com/", "Intuit", "finance", "The score, free."),
    ("annualcredit", "AnnualCreditReport", "https://www.annualcreditreport.com/", "CRAs", "finance", "The actual free report."),
    ("irs", "IRS", "https://www.irs.gov/", "IRS", "finance,business", "The form."),
    ("turbotax", "TurboTax", "https://turbotax.intuit.com/", "Intuit", "finance", "The other form."),
    ("freetaxusa", "FreeTaxUSA", "https://www.freetaxusa.com/", "FreeTaxUSA", "finance", "The cheaper form."),
    ("opencorporates", "OpenCorporates", "https://opencorporates.com/", "OC", "business,libraries", "Every company, almost."),
]
for i, n, u, d, g, t in finance:
    add(i, n, u, d, g, t)

health = [
    ("webmd", "WebMD", "https://www.webmd.com/", "WebMD", "health", "You definitely have it."),
    ("mayoclinic", "Mayo Clinic", "https://www.mayoclinic.org/", "Mayo", "health", "The serious one."),
    ("clevelandclinic", "Cleveland Clinic", "https://my.clevelandclinic.org/", "CCF", "health", "The other serious one."),
    ("healthline", "Healthline", "https://www.healthline.com/", "Healthline", "health", "The SEO of the body."),
    ("drugs", "Drugs.com", "https://www.drugs.com/", "Drugs.com", "health", "The pill, identified."),
    ("goodrx", "GoodRx", "https://www.goodrx.com/", "GoodRx", "health,finance", "The cheaper pill."),
    ("medlineplus", "MedlinePlus", "https://medlineplus.gov/", "NIH", "health,libraries", "The public library of the body."),
    ("cdc", "CDC", "https://www.cdc.gov/", "CDC", "health", "Official."),
    ("who", "WHO", "https://www.who.int/", "WHO", "health", "Geneva, speaking."),
    ("myfitnesspal", "MyFitnessPal", "https://www.myfitnesspal.com/", "Under Armour", "health", "The log."),
    ("cronometer", "Cronometer", "https://cronometer.com/", "Cronometer", "health", "The serious log."),
    ("loseit", "Lose It!", "https://www.loseit.com/", "Lose It", "health", "The other log."),
    ("noom", "Noom", "https://www.noom.com/", "Noom", "health", "Psychology, billed monthly."),
    ("headspace", "Headspace", "https://www.headspace.com/", "Headspace", "health,lifestyle", "The orange dot."),
    ("calm", "Calm", "https://www.calm.com/", "Calm", "health,lifestyle", "The blue night."),
    ("insighttimer", "Insight Timer", "https://insighttimer.com/", "Insight Timer", "health,lifestyle", "The free cushion."),
    ("tenpercent", "Ten Percent Happier", "https://www.tenpercent.com/", "10%", "health", "Skeptics, sitting."),
    ("peloton", "Peloton", "https://www.onepeloton.com/", "Peloton", "health", "The bike, as a tab."),
    ("nike-run", "Nike Run Club", "https://www.nike.com/nrc-app", "Nike", "health", "The coach."),
    ("adidas-running", "adidas Running", "https://www.runtastic.com/", "adidas", "health", "Runtastic, renamed."),
    ("garmin-connect", "Garmin Connect", "https://connect.garmin.com/", "Garmin", "health", "The watch’s website."),
    ("fitbit", "Fitbit", "https://www.fitbit.com/", "Google", "health", "The other watch’s website."),
    ("oura", "Oura", "https://ouraring.com/", "Oura", "health", "The ring."),
    ("whoop", "WHOOP", "https://www.whoop.com/", "WHOOP", "health", "The strap."),
    ("zwift", "Zwift", "https://www.zwift.com/", "Zwift", "health,games", "The basement Tour."),
    ("trainerroad", "TrainerRoad", "https://www.trainerroad.com/", "TR", "health", "Intervals, serious."),
    ("flo", "Flo", "https://flo.health/", "Flo", "health", "The cycle."),
    ("clue", "Clue", "https://helloclue.com/", "Clue", "health", "The other cycle."),
    ("babycenter", "BabyCenter", "https://www.babycenter.com/", "BabyCenter", "health,lifestyle", "The week-by-week."),
    ("whattoexpect", "What to Expect", "https://www.whattoexpect.com/", "WTE", "health,lifestyle", "The other week-by-week."),
    ("sleepfoundation", "Sleep Foundation", "https://www.sleepfoundation.org/", "NSF", "health", "The hours you don’t get."),
    ("sleepcycle", "Sleep Cycle", "https://www.sleepcycle.com/", "Sleep Cycle", "health", "The alarm that waits."),
]
for i, n, u, d, g, t in health:
    add(i, n, u, d, g, t)

social = [
    ("facebook", "Facebook", "https://www.facebook.com/", "Meta", "social", "The original feed."),
    ("messenger", "Messenger", "https://www.messenger.com/", "Meta", "communication", "The chat that split off."),
    ("snapchat", "Snapchat", "https://www.snapchat.com/", "Snap", "social,communication", "The ghost."),
    ("reddit-chat", "Reddit", "https://www.reddit.com/", "Reddit", "social,news", "The front page, still."),
    ("mastodon", "Mastodon", "https://mastodon.social/", "Mastodon", "social", "The federated town square."),
    ("bluesky-app", "Bluesky", "https://bsky.app/", "Bluesky", "social", "The sky, again."),
    ("threads-app", "Threads", "https://www.threads.net/", "Meta", "social", "The shorter timeline."),
    ("truthsocial", "Truth Social", "https://truthsocial.com/", "TMTG", "social", "The other square."),
    ("bereal", "BeReal", "https://bereal.com/", "BeReal", "social", "Two minutes a day."),
    ("glass", "Glass", "https://glass.photo/", "Glass", "photo,social", "Photos, without the circus."),
    ("vsco", "VSCO", "https://www.vsco.co/", "VSCO", "photo,social", "The filter that was a personality."),
    ("flickr", "Flickr", "https://www.flickr.com/", "SmugMug", "photo,social", "The archive of a decade."),
    ("500px", "500px", "https://500px.com/", "500px", "photo,social", "The other archive."),
    ("unsplash", "Unsplash", "https://unsplash.com/", "Unsplash", "photo,libraries", "Free photos, mostly."),
    ("pexels", "Pexels", "https://www.pexels.com/", "Pexels", "photo,libraries", "The other free photos."),
    ("pixabay", "Pixabay", "https://pixabay.com/", "Pixabay", "photo,libraries", "Yet more free photos."),
    ("wechat", "WeChat Web", "https://web.wechat.com/", "Tencent", "communication", "The super-app’s window."),
    ("line", "LINE", "https://line.me/", "LY", "communication", "The bear."),
    ("viber", "Viber", "https://www.viber.com/", "Rakuten", "communication", "The purple chat."),
    ("skype", "Skype", "https://web.skype.com/", "Microsoft", "communication,video", "The one we forgot."),
    ("teams", "Microsoft Teams", "https://teams.microsoft.com/", "Microsoft", "communication,business", "The meeting after the meeting."),
    ("webex", "Webex", "https://www.webex.com/", "Cisco", "communication,business", "The older meeting."),
    ("gotomeeting", "GoTo", "https://www.goto.com/", "GoTo", "communication,business", "The even older meeting."),
    ("jitsi", "Jitsi", "https://meet.jit.si/", "8x8", "communication,video", "The meeting with no account."),
    ("whereby", "Whereby", "https://whereby.com/", "Whereby", "communication,video", "A link is the room."),
    ("loom", "Loom", "https://www.loom.com/", "Atlassian", "video,communication", "The async face."),
    ("mmhmm", "mmhmm", "https://www.mmhmm.app/", "mmhmm", "video,communication", "The presenter, staged."),
    ("cal-com", "Cal.com", "https://cal.com/", "Cal.com", "productivity,business", "The open Calendly."),
    ("savvycal", "SavvyCal", "https://savvycal.com/", "SavvyCal", "productivity,business", "The polite calendar."),
    ("doodle", "Doodle", "https://doodle.com/", "Doodle", "productivity", "When works."),
    ("when2meet", "when2meet", "https://www.when2meet.com/", "when2meet", "productivity", "The grid of availability."),
    ("letterboxd-social", "Letterboxd people", "https://letterboxd.com/welcome/", "Letterboxd", "social,entertainment", "Friends who watch."),
]
for i, n, u, d, g, t in social:
    add(i, n, u, d, g, t)

prod = [
    ("clickup", "ClickUp", "https://clickup.com/", "ClickUp", "productivity,business", "The one app to replace them."),
    ("monday", "monday.com", "https://monday.com/", "monday", "productivity,business", "Colorful work."),
    ("smartsheet", "Smartsheet", "https://www.smartsheet.com/", "Smartsheet", "productivity,business", "Sheets that act like projects."),
    ("jira", "Jira", "https://www.atlassian.com/software/jira", "Atlassian", "productivity,business", "The ticket."),
    ("confluence", "Confluence", "https://www.atlassian.com/software/confluence", "Atlassian", "productivity,business", "The wiki at work."),
    ("notion-calendar2", "Notion", "https://www.notion.so/", "Notion", "productivity", "The doc that ate the office."),
    ("height", "Height", "https://height.app/", "Height", "productivity,business", "Autopilot projects."),
    ("shortcut", "Shortcut", "https://www.shortcut.com/", "Shortcut", "productivity,tools", "Clubhouse, renamed."),
    ("basecamp", "Basecamp", "https://basecamp.com/", "37signals", "productivity,business", "The calm company tool."),
    ("hey", "HEY", "https://www.hey.com/", "37signals", "communication", "Email, with opinions."),
    ("fastmail", "Fastmail", "https://www.fastmail.com/", "Fastmail", "communication", "Paid email, unapologetic."),
    ("tuta", "Tuta", "https://tuta.com/", "Tuta", "communication", "Encrypted, German."),
    ("proton-calendar", "Proton Calendar", "https://calendar.proton.me/", "Proton", "productivity", "The private week."),
    ("proton-drive", "Proton Drive", "https://drive.proton.me/", "Proton", "productivity,tools", "The private folder."),
    ("mega", "MEGA", "https://mega.nz/", "MEGA", "tools", "The 50GB pitch."),
    ("pcloud", "pCloud", "https://www.pcloud.com/", "pCloud", "tools", "Swiss-ish storage."),
    ("box", "Box", "https://www.box.com/", "Box", "business,productivity", "Enterprise folders."),
    ("onedrive", "OneDrive", "https://onedrive.live.com/", "Microsoft", "productivity", "The folder in Windows."),
    ("icloud", "iCloud", "https://www.icloud.com/", "Apple", "productivity", "The folder in Cupertino."),
    ("google-keep", "Google Keep", "https://keep.google.com/", "Google", "productivity", "Yellow notes."),
    ("google-tasks", "Google Tasks", "https://tasks.google.com/", "Google", "productivity", "The list in Gmail’s side."),
    ("google-contacts", "Google Contacts", "https://contacts.google.com/", "Google", "communication", "The address book."),
    ("google-photos", "Google Photos", "https://photos.google.com/", "Google", "photo", "The attic."),
    ("flickr-pro", "Flickr Pro", "https://www.flickr.com/help/limits", "SmugMug", "photo", "The paid attic."),
    ("frame-io", "Frame.io", "https://www.frame.io/", "Adobe", "video,business", "Review the cut."),
    ("descript", "Descript", "https://www.descript.com/", "Descript", "video,tools", "Edit the transcript."),
    ("runway", "Runway", "https://runwayml.com/", "Runway", "video,tools", "Video, generated."),
    ("pika", "Pika", "https://pika.art/", "Pika", "video,tools", "The other generated video."),
    ("luma", "Luma", "https://lumalabs.ai/", "Luma", "video,tools", "Dream Machine."),
    ("kling", "Kling", "https://klingai.com/", "Kuaishou", "video,tools", "The other dream."),
    ("suno", "Suno", "https://suno.com/", "Suno", "music,tools", "A song from a sentence."),
    ("udio", "Udio", "https://www.udio.com/", "Udio", "music,tools", "The other song."),
    ("elevenlabs", "ElevenLabs", "https://elevenlabs.io/", "ElevenLabs", "tools", "A voice from text."),
    ("play-ht", "Play.ht", "https://play.ht/", "PlayHT", "tools", "The other voice."),
    ("midjourney", "Midjourney", "https://www.midjourney.com/", "Midjourney", "photo,tools", "The discord that makes pictures."),
    ("leonardo", "Leonardo", "https://leonardo.ai/", "Leonardo", "photo,tools", "The other pictures."),
    ("ideogram", "Ideogram", "https://ideogram.ai/", "Ideogram", "photo,tools", "Text, actually spelled."),
    ("recraft", "Recraft", "https://www.recraft.ai/", "Recraft", "photo,tools", "Vectors, generated."),
    ("krea", "Krea", "https://www.krea.ai/", "Krea", "photo,tools", "Realtime images."),
    ("huggingface-spaces", "Hugging Face Spaces", "https://huggingface.co/spaces", "Hugging Face", "tools,education", "Demos, public."),
    ("replicate", "Replicate", "https://replicate.com/", "Replicate", "tools", "Run the model."),
    ("together", "Together", "https://www.together.ai/", "Together", "tools", "The other run."),
    ("groq", "Groq", "https://groq.com/", "Groq", "tools", "Tokens, fast."),
    ("openrouter2", "OpenRouter", "https://openrouter.ai/", "OpenRouter", "tools", "One key, many models."),
    ("poe", "Poe", "https://poe.com/", "Quora", "tools", "A room of models."),
    ("you", "You.com", "https://you.com/", "You", "tools", "Search, with a sidebar."),
    ("phind", "Phind", "https://www.phind.com/", "Phind", "tools,education", "Search for people who code."),
    ("kagi", "Kagi", "https://kagi.com/", "Kagi", "tools", "Search, paid, blessedly."),
    ("brave-search", "Brave Search", "https://search.brave.com/", "Brave", "tools", "The other index."),
    ("startpage", "Startpage", "https://www.startpage.com/", "Startpage", "tools", "Google, anonymized."),
    ("duckduckgo", "DuckDuckGo", "https://duckduckgo.com/", "DuckDuckGo", "tools", "The duck."),
    ("ecosia", "Ecosia", "https://www.ecosia.org/", "Ecosia", "tools", "Search, plant."),
    ("wikipedia-simple", "Simple Wikipedia", "https://simple.wikipedia.org/", "Wikimedia", "education,libraries", "English, slower."),
    ("wikihow", "wikiHow", "https://www.wikihow.com/", "wikiHow", "education,lifestyle", "How to, illustrated."),
    ("instructables", "Instructables", "https://www.instructables.com/", "Autodesk", "education,lifestyle", "How to, with a laser cutter."),
    ("thingiverse", "Thingiverse", "https://www.thingiverse.com/", "MakerBot", "tools,lifestyle", "The STL attic."),
    ("printables", "Printables", "https://www.printables.com/", "Prusa", "tools,lifestyle", "The other STL attic."),
    ("makerworld", "MakerWorld", "https://makerworld.com/", "Bambu", "tools,lifestyle", "The new STL attic."),
]
for i, n, u, d, g, t in prod:
    add(i, n, u, d, g, t)

# still more to push toward 1000
extra = [
    ("obsidian", "Obsidian", "https://obsidian.md/", "Obsidian", "productivity", "Local files, linked."),
    ("roam", "Roam Research", "https://roamresearch.com/", "Roam", "productivity", "The graph that started it."),
    ("remnote", "RemNote", "https://www.remnote.com/", "RemNote", "education,productivity", "Notes that become cards."),
    ("tana", "Tana", "https://tana.inc/", "Tana", "productivity", "Outliner 3.0."),
    ("heptabase", "Heptabase", "https://heptabase.com/", "Heptabase", "productivity,education", "Cards on a white desk."),
    ("scrintal", "Scrintal", "https://scrintal.com/", "Scrintal", "productivity", "The other white desk."),
    ("milanote", "Milanote", "https://milanote.com/", "Milanote", "productivity,photo", "Mood boards for work."),
    ("mural", "Mural", "https://www.mural.co/", "Mural", "productivity,business", "The other wall."),
    ("figjam", "FigJam", "https://www.figma.com/figjam/", "Figma", "productivity", "Sticky notes, official."),
    ("freeform", "Apple Freeform", "https://www.apple.com/freeform/", "Apple", "productivity", "The board in iOS."),
    ("photopea-learn", "Photopea Learn", "https://www.photopea.com/learn/", "Photopea", "photo,education", "The manual."),
    ("photopea-api", "Photopea", "https://www.photopea.com/#api", "Photopea", "photo,tools", "The editor, still."),
    ("pixlr-e", "Pixlr E", "https://pixlr.com/e/", "Pixlr", "photo", "The other editor."),
    ("pixlr-x", "Pixlr X", "https://pixlr.com/x/", "Pixlr", "photo", "The simpler editor."),
    ("photo-editor", "Photopea alternatives list", "https://www.photopea.com/", "Photopea", "photo", "Stay here."),
    ("sumopaint", "Sumo Paint", "https://sumo.app/paint", "Sumo", "photo", "Flash’s painting child."),
    ("kleki", "Kleki", "https://kleki.com/", "Kleki", "photo", "Paint, no account."),
    ("jspaint", "JS Paint", "https://jspaint.app/", "1j01", "photo,tools", "Mspaint, resurrected."),
    ("window-swap-2", "Window-Swap", "https://www.window-swap.com/", "WindowSwap", "lifestyle,travel", "A window, somewhere."),
    ("slowroads", "slow roads", "https://slowroads.io/", "anslo", "games,lifestyle", "Drive. No score."),
    ("pointer-pointer", "Pointer Pointer", "https://pointerpointer.com/", "Patrick", "entertainment", "It finds your mouse."),
    ("theuselessweb", "The Useless Web", "https://theuselessweb.com/", "Useless", "entertainment", "A button to nowhere."),
    ("hackertyper", "Hacker Typer", "https://hackertyper.com/", "HackerTyper", "entertainment,games", "Look busy."),
    ("cat-bounce", "Cat Bounce", "https://cat-bounce.com/", "Cat Bounce", "entertainment,kids", "Cats. Bouncing."),
    ("placekitten", "placekitten", "https://placekitten.com/", "placekitten", "tools,photo", "Kittens as placeholders."),
    ("placehold", "placeholder.com", "https://placeholder.com/", "placeholder", "tools", "Grey boxes."),
    ("loremflickr", "Lorem Flickr", "https://loremflickr.com/", "loremflickr", "tools,photo", "Photos as Lorem."),
    ("picsum", "Lorem Picsum", "https://picsum.photos/", "Picsum", "tools,photo", "The nicer placeholder."),
    ("httpstat", "httpstat.us", "https://httpstat.us/", "httpstat", "tools", "Status codes, on demand."),
    ("httpbin", "httpbin", "https://httpbin.org/", "Postman", "tools", "The request echo."),
    ("postman-web", "Postman", "https://web.postman.co/", "Postman", "tools", "The collection."),
    ("insomnia", "Insomnia", "https://insomnia.rest/", "Kong", "tools", "The other collection."),
    ("rapidapi", "RapidAPI", "https://rapidapi.com/", "Rapid", "tools,business", "The API bazaar."),
    ("publicapis", "Public APIs", "https://github.com/public-apis/public-apis", "public-apis", "tools,libraries", "A list of doors."),
    ("devdocs2", "DevDocs", "https://devdocs.io/", "DevDocs", "education,tools", "Docs, offline-able."),
    ("zeal", "Zeal", "https://zealdocs.org/", "Zeal", "education,tools", "Dash, for the rest of us."),
    ("tldr", "tldr pages", "https://tldr.sh/", "tldr", "education,tools", "Man pages, shorter."),
    ("explainshell", "explainshell", "https://explainshell.com/", "explainshell", "education,tools", "A command, taken apart."),
    ("ss64", "SS64", "https://ss64.com/", "SS64", "education,libraries", "Every command, remembered."),
    ("caniuse2", "Can I Use", "https://caniuse.com/", "caniuse", "tools", "Support tables."),
    ("whatwg", "WHATWG", "https://html.spec.whatwg.org/", "WHATWG", "libraries,education", "The living standard."),
    ("w3c", "W3C", "https://www.w3.org/", "W3C", "libraries,education", "The other standard."),
    ("ietf", "IETF", "https://www.ietf.org/", "IETF", "libraries", "The RFCs."),
    ("rfc-editor", "RFC Editor", "https://www.rfc-editor.org/", "RFC Editor", "libraries", "The numbered papers."),
]
for i, n, u, d, g, t in extra:
    add(i, n, u, d, g, t)

# pad with country news + public broadcasters + big retailers + gov
pad = [
    ("usatoday", "USA Today", "https://www.usatoday.com/", "Gannett", "news", "The colorful paper."),
    ("usnews", "U.S. News", "https://www.usnews.com/", "USNWR", "news,education", "The ranking people."),
    ("forbes", "Forbes", "https://www.forbes.com/", "Forbes", "news,finance", "The list."),
    ("fortune", "Fortune", "https://fortune.com/", "Fortune", "news,business", "The other list."),
    ("inc", "Inc.", "https://www.inc.com/", "Inc", "news,business", "Founders, profiled."),
    ("fastcompany", "Fast Company", "https://www.fastcompany.com/", "Mansueto", "news,business", "Design as business."),
    ("hbr", "Harvard Business Review", "https://hbr.org/", "HBR", "business,education", "The case study."),
    ("mittr", "MIT Tech Review", "https://www.technologyreview.com/", "MIT", "news,education", "The serious gadget paper."),
    ("nature", "Nature", "https://www.nature.com/", "Springer", "education,news", "The journal."),
    ("science", "Science", "https://www.science.org/", "AAAS", "education,news", "The other journal."),
    ("newscientist", "New Scientist", "https://www.newscientist.com/", "NS", "education,news", "The magazine."),
    ("scientificamerican", "Scientific American", "https://www.scientificamerican.com/", "Springer", "education,news", "The old magazine."),
    ("nationalgeographic", "National Geographic", "https://www.nationalgeographic.com/", "Disney", "education,travel", "Yellow border."),
    ("smithsonian", "Smithsonian", "https://www.smithsonianmag.com/", "Smithsonian", "education", "The castle’s magazine."),
    ("nasa", "NASA", "https://www.nasa.gov/", "NASA", "education,news", "The sky, official."),
    ("esa", "ESA", "https://www.esa.int/", "ESA", "education", "Europe’s sky."),
    ("spacex", "SpaceX", "https://www.spacex.com/", "SpaceX", "business,education", "The other sky."),
    ("starlink", "Starlink", "https://www.starlink.com/", "SpaceX", "business", "The dish."),
    ("tesla", "Tesla", "https://www.tesla.com/", "Tesla", "shopping,business", "The car, as a site."),
    ("rivian", "Rivian", "https://www.rivian.com/", "Rivian", "shopping", "The other truck."),
    ("ford", "Ford", "https://www.ford.com/", "Ford", "shopping", "The blue oval."),
    ("gm", "GM", "https://www.gm.com/", "GM", "shopping,business", "The other oval."),
    ("toyota", "Toyota", "https://www.toyota.com/", "Toyota", "shopping", "The reliable one."),
    ("honda", "Honda", "https://www.honda.com/", "Honda", "shopping", "The other reliable one."),
    ("cars", "Cars.com", "https://www.cars.com/", "Cars.com", "shopping", "A car, listed."),
    ("autotrader", "Autotrader", "https://www.autotrader.com/", "Cox", "shopping", "The other listing."),
    ("cargurus", "CarGurus", "https://www.cargurus.com/", "CarGurus", "shopping", "The deal, graphed."),
    ("kbb", "Kelley Blue Book", "https://www.kbb.com/", "Cox", "shopping,finance", "What it’s worth."),
    ("edmunds", "Edmunds", "https://www.edmunds.com/", "Edmunds", "shopping", "The review of the car."),
    ("craigslist", "Craigslist", "https://www.craigslist.org/", "Craigslist", "shopping", "The list that built the web."),
    ("facebook-marketplace", "Marketplace", "https://www.facebook.com/marketplace/", "Meta", "shopping", "The other list."),
    ("offerup", "OfferUp", "https://offerup.com/", "OfferUp", "shopping", "The local listing."),
    ("mercari", "Mercari", "https://www.mercari.com/", "Mercari", "shopping", "The Japanese listing."),
    ("vinted", "Vinted", "https://www.vinted.com/", "Vinted", "shopping", "The closet, European."),
    ("leboncoin", "Leboncoin", "https://www.leboncoin.fr/", "LBC", "shopping", "France’s list."),
    ("gumtree", "Gumtree", "https://www.gumtree.com/", "Gumtree", "shopping", "UK’s list."),
    ("trademe", "Trade Me", "https://www.trademe.co.nz/", "Trade Me", "shopping", "New Zealand’s list."),
    ("kijiji", "Kijiji", "https://www.kijiji.ca/", "eBay", "shopping", "Canada’s list."),
    ("olx", "OLX", "https://www.olx.com/", "OLX", "shopping", "A lot of countries’ list."),
    ("avito", "Avito", "https://www.avito.ru/", "Avito", "shopping", "The other list, east."),
]
for i, n, u, d, g, t in pad:
    add(i, n, u, d, g, t)

# de-dupe by id
seen = set()
uniq = []
for row in ROWS:
    if row[0] in seen:
        continue
    seen.add(row[0])
    uniq.append(row)

out = Path("/workspace/src/lib/catalog-more.ts")
lines = [
    "/** Auto-generated extra listings. Real sites. Favicon pulled from the URL. */",
    "export const MORE: {",
    "  id: string; name: string; url: string; developer: string; genres: string[]; tagline: string;",
    "}[] = [",
]
for i, name, url, dev, genres, tag in uniq:
    gs = ", ".join(f'"{g.strip()}"' for g in genres.split(","))
    tag_esc = tag.replace("\\", "\\\\").replace('"', '\\"')
    name_esc = name.replace('"', '\\"')
    dev_esc = dev.replace('"', '\\"')
    lines.append(
        f'  {{ id: "{i}", name: "{name_esc}", url: "{url}", developer: "{dev_esc}", genres: [{gs}], tagline: "{tag_esc}" }},'
    )
lines.append("];")
lines.append("")
out.write_text("\n".join(lines))
print("wrote", len(uniq), "to", out)


