/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as BetaRouteImport } from './routes/beta'
import { Route as CensusRouteImport } from './routes/census'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as FindRouteImport } from './routes/find'
import { Route as FlintsRouteImport } from './routes/flints'
import { Route as ForgeRouteImport } from './routes/forge'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as WellRouteImport } from './routes/well'
import { Route as AppIdRouteImport } from './routes/app.$id'
import { Route as CategoryGenreRouteImport } from './routes/category.$genre'
import { Route as MakerSlugRouteImport } from './routes/maker.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const CensusRoute = CensusRouteImport.update({
  id: '/census',
  path: '/census',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const FlintsRoute = FlintsRouteImport.update({
  id: '/flints',
  path: '/flints',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WellRoute = WellRouteImport.update({
  id: '/well',
  path: '/well',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIdRoute = AppIdRouteImport.update({
  id: '/app/$id',
  path: '/app/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryGenreRoute = CategoryGenreRouteImport.update({
  id: '/category/$genre',
  path: '/category/$genre',
  getParentRoute: () => rootRouteImport,
} as any)
const MakerSlugRoute = MakerSlugRouteImport.update({
  id: '/maker/$slug',
  path: '/maker/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advertise': typeof AdvertiseRoute
  '/alerts': typeof AlertsRoute
  '/beta': typeof BetaRoute
  '/census': typeof CensusRoute
  '/contact': typeof ContactRoute
  '/desk': typeof DeskRoute
  '/find': typeof FindRoute
  '/flints': typeof FlintsRoute
  '/forge': typeof ForgeRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/people': typeof PeopleRoute
  '/saved': typeof SavedRoute
  '/studio': typeof StudioRoute
  '/well': typeof WellRoute
  '/app/$id': typeof AppIdRoute
  '/category/$genre': typeof CategoryGenreRoute
  '/maker/$slug': typeof MakerSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advertise': typeof AdvertiseRoute
  '/alerts': typeof AlertsRoute
  '/beta': typeof BetaRoute
  '/census': typeof CensusRoute
  '/contact': typeof ContactRoute
  '/desk': typeof DeskRoute
  '/find': typeof FindRoute
  '/flints': typeof FlintsRoute
  '/forge': typeof ForgeRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/people': typeof PeopleRoute
  '/saved': typeof SavedRoute
  '/studio': typeof StudioRoute
  '/well': typeof WellRoute
  '/app/$id': typeof AppIdRoute
  '/category/$genre': typeof CategoryGenreRoute
  '/maker/$slug': typeof MakerSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advertise': typeof AdvertiseRoute
  '/alerts': typeof AlertsRoute
  '/beta': typeof BetaRoute
  '/census': typeof CensusRoute
  '/contact': typeof ContactRoute
  '/desk': typeof DeskRoute
  '/find': typeof FindRoute
  '/flints': typeof FlintsRoute
  '/forge': typeof ForgeRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/people': typeof PeopleRoute
  '/saved': typeof SavedRoute
  '/studio': typeof StudioRoute
  '/well': typeof WellRoute
  '/app/$id': typeof AppIdRoute
  '/category/$genre': typeof CategoryGenreRoute
  '/maker/$slug': typeof MakerSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advertise'
    | '/alerts'
    | '/beta'
    | '/census'
    | '/contact'
    | '/desk'
    | '/find'
    | '/flints'
    | '/forge'
    | '/games'
    | '/login'
    | '/me'
    | '/people'
    | '/saved'
    | '/studio'
    | '/well'
    | '/app/$id'
    | '/category/$genre'
    | '/maker/$slug'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advertise'
    | '/alerts'
    | '/beta'
    | '/census'
    | '/contact'
    | '/desk'
    | '/find'
    | '/flints'
    | '/forge'
    | '/games'
    | '/login'
    | '/me'
    | '/people'
    | '/saved'
    | '/studio'
    | '/well'
    | '/app/$id'
    | '/category/$genre'
    | '/maker/$slug'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/advertise'
    | '/alerts'
    | '/beta'
    | '/census'
    | '/contact'
    | '/desk'
    | '/find'
    | '/flints'
    | '/forge'
    | '/games'
    | '/login'
    | '/me'
    | '/people'
    | '/saved'
    | '/studio'
    | '/well'
    | '/app/$id'
    | '/category/$genre'
    | '/maker/$slug'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvertiseRoute: typeof AdvertiseRoute
  AlertsRoute: typeof AlertsRoute
  BetaRoute: typeof BetaRoute
  CensusRoute: typeof CensusRoute
  ContactRoute: typeof ContactRoute
  DeskRoute: typeof DeskRoute
  FindRoute: typeof FindRoute
  FlintsRoute: typeof FlintsRoute
  ForgeRoute: typeof ForgeRoute
  GamesRoute: typeof GamesRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  PeopleRoute: typeof PeopleRoute
  SavedRoute: typeof SavedRoute
  StudioRoute: typeof StudioRoute
  WellRoute: typeof WellRoute
  AppIdRoute: typeof AppIdRoute
  CategoryGenreRoute: typeof CategoryGenreRoute
  MakerSlugRoute: typeof MakerSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/census': {
      id: '/census'
      path: '/census'
      fullPath: '/census'
      preLoaderRoute: typeof CensusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flints': {
      id: '/flints'
      path: '/flints'
      fullPath: '/flints'
      preLoaderRoute: typeof FlintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/well': {
      id: '/well'
      path: '/well'
      fullPath: '/well'
      preLoaderRoute: typeof WellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$id': {
      id: '/app/$id'
      path: '/app/$id'
      fullPath: '/app/$id'
      preLoaderRoute: typeof AppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$genre': {
      id: '/category/$genre'
      path: '/category/$genre'
      fullPath: '/category/$genre'
      preLoaderRoute: typeof CategoryGenreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maker/$slug': {
      id: '/maker/$slug'
      path: '/maker/$slug'
      fullPath: '/maker/$slug'
      preLoaderRoute: typeof MakerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvertiseRoute: AdvertiseRoute,
  AlertsRoute: AlertsRoute,
  BetaRoute: BetaRoute,
  CensusRoute: CensusRoute,
  ContactRoute: ContactRoute,
  DeskRoute: DeskRoute,
  FindRoute: FindRoute,
  FlintsRoute: FlintsRoute,
  ForgeRoute: ForgeRoute,
  GamesRoute: GamesRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  PeopleRoute: PeopleRoute,
  SavedRoute: SavedRoute,
  StudioRoute: StudioRoute,
  WellRoute: WellRoute,
  AppIdRoute: AppIdRoute,
  CategoryGenreRoute: CategoryGenreRoute,
  MakerSlugRoute: MakerSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
